### ISSUE TITLE
Support authentication via Shared Access Signatures (SAS) for Azure artifacts

### ISSUE THREAD

**Issue by alexdittmann** [argoproj/argo-workflows#10297]
# Summary

Support authentication via Shared Access Signatures (SAS) for Azure artifacts

# Use Cases

With argo v3.4 support for Azure artifacts has been implemented. As far as I understand, the current implementation only supports authentication via [Storage Account access keys](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=azure-portal), but not via [Shared Access Signatures (SAS)](https://learn.microsoft.com/en-us/azure/storage/blobs/sas-service-create?tabs=dotnet). 
I would like to be able to use SAS  for authentication, too. 

@brianloss Since you worked on this feature, could you confirm that I am right why my assumption? I could not find a way to make it work with SAS tokens. (and thanks btw for implementing it!)

Me/my team would potentially be willing do this contribution.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by brianloss** [comment]
@alexdittmann the underlying authentication uses the Azure SDK for Go, and the [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#defaultazurecredential) in particular. This supports authentication via [environment variables](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#environment-variables), Workload Identity, Managed Identity, or Azure CLI. (See [this learn page](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication) for more details as well.) This is all enabled by setting `UseSDKCreds` to `true`. Otherwise, the authentication method is shared access key. So, although more than just access key access is supported, SAS is not one of the supported methods. This is primarily because SAS tokens are effectively just additional query parameters added to the URL.

You could try to add the SAS token to the endpoint field and set `UseSDKCreds` to `true` to use the DefaultAzureCredential, but I'm guessing that might fail since you wouldn't actually provide any credentials. You'd likely also need to call `azblob.NewContainerClientWithNoCredential` instead of `azblob.NewContainerClient` or `azblob.NewContainerClientWithSharedKey` in the [newAzureContainerClient](https://github.com/argoproj/argo-workflows/blob/release-3.4/workflow/artifacts/azure/azure.go#L39) method when you want to use a SAS.

**Comment by missingcharacter** [comment]
I want to clarify that `Workload Identity` is not yet supported as of `azure-sdk-for-go/sdk/azidentity` version `1.2.1`, which is the version `argo-workflows` version `3.4.5` uses at the moment.

https://github.com/argoproj/argo-workflows/blob/1322f26272b403bb300f276b808a43ba1db136dc/go.mod#L7

**Comment by zsfarkas** [comment]
It's a pity. We would have used this feature with Azure ManagedIdentity very gladly. This is actually the suggested and easiest way to access storage from kubernetes.

**Comment by brianloss** [comment]
Ah, it looks like that feature in the Go SDK is still in beta. Not sure if a PR with a beta version of identity would be accepted or not, but it would be a fairly simple change to make if anyone has time to test it out.

**Comment by alexdittmann** [comment]
Hi,
I would like to bring this issue up again. We (my team) have created it in the past and would now like to look into this issue.
However, regarding contributions to the artifacts area i have one question: In the past I asked a similar question about contributing to the argo workflows artifacts codebase (see [this slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1700463409099429?thread_ts=1700235520.113979&cid=C01QW9QSSSK)) and from that I understood that argo wants to minimize new artifact functionality.
Now, this contribution here would only extend an already existing artifact type (azure) by an additional authentication method. 
So my question is: Would such a contribution have a general chance of being accepted? 
@agilgur5 maybe you can comment on this again?

Thank you and best regards
alex

**Comment by agilgur5** [comment]
Yes, as I wrote in that Slack thread too, extending existing functionality is likely to be accepted. Similarly as I wrote there, the spec etc is still important; I haven't read this issue in much detail to comment.

If we externalize artifact plugins (#5862), some may still be "core" plugins that are built-in or more closely maintained, and the main "hyperscaler" clouds are the most popular to support.

**Comment by kavishdahekar-sap** [comment]
Hi @brianloss and @agilgur5 , I am a part of @alexdittmann 's team currently working on a proposal for the support of Azure SAS tokens.

Could you please quickly verify one of these approaches as possibly suitable for moving forward with this contribution?

1. For supporting azure SAS tokens, we do not introduce any spec changes, instead when reading the `AccountKeySecret`, the Azure `ArtifactDriver` will parse the secret string to check for query param structure (`&<param-name>=<param-value>`) to determine whether the provided secret is a SAS token. Is yes, the driver will internally initialize a `NewContainerClientWithNoCredential`.

2. We introduce a new boolean spec param `useSASToken` which the Azure artifact driver will use for determining whether to consider the contents of `AccountKeySecret` as a SAS token.

**Comment by alexdittmann** [comment]
Hi again @agilgur5,
do you have any opinion on the query of @kavishdahekar-sap or could tell us where we could get some additional feedback?
Otherwise, as we would like to implement this soon, we just start implementing option 1.

Thank you and best
Alex

**Comment by kavishdahekar-sap** [comment]
Could I get a review here please?
https://github.com/argoproj/argo-workflows/pull/13360

**Comment by brianloss** [comment]
@kavishdahekar-sap I'm not a committer, but I can take a look.
