### ISSUE TITLE
Git artifact directory is missing

### ISSUE THREAD

**Issue by 66li** [argoproj/argo-workflows#10611]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

git artifact repo  
/public dir not fount

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
aa
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
aa
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
aa
```

**Comment by tico24** [comment]
Could you please provide more information so that we can better understand this?

**Comment by 66li** [comment]
argoexec:v3.4.5 

inint git artifact
The public directory in the source warehouse is missing

Is it related to the directory name or the depth of the directory

**Comment by 66li** [comment]
> Could you please provide more information so that we can better understand this?

My English is not very good.

I have a public directory in the source git repo

But after pulling it with git artifact, the public directory disappeared, but there is no error log

**Comment by liangyuanpeng** [comment]
@JPZ13  Could you please provide some code and yaml to reproduce it?

**Comment by agilgur5** [comment]
> When using the depth parameter, directories in the source repository will be lost

This sounds like they used the [`depth` field](https://argo-workflows.readthedocs.io/en/latest/fields/#gitartifact), i.e. `git clone --depth` for a shallow clone and then they were missing a directory in their cloned repo.

`go-git` does [support `--depth`](https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md#getting-and-creating-repositories), which is why it's exposed.

In any case, without a reproducible, buggy Workflow, it is not really possible to debug. It may also have been fixed in newer versions of Argo and `go-git` at this point.
