### ISSUE TITLE
Enable Branch Protections on Github

### ISSUE THREAD

**Issue by ryancurrah** [argoproj/argo-workflows#10722]
# Summary

We are in the process of getting Argo Workflows approved for use in our company. Our security review team let us know that Argo Workflows does not have branch protections enabled.

# Use Cases

Protect important branches by setting branch protection rules, which define whether collaborators can delete or force push to the branch and set requirements for any pushes to the branch, such as passing status checks or a linear commit history.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule

The minimal amount of protections could be.

- Require a review before merging and require at least one approval.
- Restrict who can push to the default primary branch `master`. Or just disallow everyone from pushing directly to it.
- Do not allow force pushes on the default primary branch `master`.
- Do not allow deletions on the default primary branch `master`.
- Do not allow bypassing the above settings.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by ryancurrah** [comment]
Interesting ok I will provide this to our team. Thank you.

**Comment by caelan-io** [comment]
The quick takeaway snapshot of the PDF Alex uploaded: 
<img width="613" alt="Screen Shot 2023-03-21 at 5 44 10 PM src="https://user-images.githubusercontent.com/45773958/226696585-1fe8dbe6-7507-4634-9114-2b4e1264d9cc.png">

"Do not allow bypassing the above settings" is also enabled.

@ryancurrah - what specific changes are you proposing beyond these settings in the PDF? 

Also note that all 4 major Argo projects recently passed a security review in order to graduate within the CNCF. [Blog post](https://blog.argoproj.io/2022-argo-external-security-audit-lessons-learned-951f80e0450d). [Talk](https://www.youtube.com/watch?v=EilOEF4gs0c).

**Comment by ryancurrah** [comment]
I just asked what our security team used to detect this and they said they used https://securityscorecards.dev. Though they just mentioned it wasn't a branch protection that it failed on it was...

> Scored 0/10 for token permissions
> A non read-only token was detected in a workflow of this repository
> Setting token permissions to read-only whenever possible follows the principle of least privilege
> This is important because attackers may use a compromised token with write access to make unauthorized changes to the repository and codebase
