### ISSUE TITLE
CVE-2022-41722 | CVE-2022-41723 Facing vulnerable issues with golang, golang.org/net versions in argocli 

### ISSUE THREAD

**Issue by kalpanathanneeru21** [argoproj/argo-workflows#10811]
# Summary

Facing vulnerable issues with golang, golang.org/net versions in argocli  since they are older/outdated versions.
current env:
argo-workflows - 3.4.6
argo-cli : 3.4.6
Kubernetes version - EKS 1.22

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/85505383/229742468-30c291f2-e1cc-4ea3-94f4-04212991e4ab.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/85505383/229742628-81775787-4d93-4e06-a451-6a81b32fa76d.png">

We need this to be fixed as early as possible.
Is there any latest releases are going to cover this.

**Comment by caelan-io** [comment]
Thanks for raising. So `master` is running go 1.19 (https://github.com/argoproj/argo-workflows/blob/master/go.mod#L3). I'm not 100% sure why the latest release tag isn't. It's probably because this would be a material update that we want to test thoroughly and save for a minor release, i.e. version 3.5  - We will look into it and post updates as we have them.

Answering your question: If you want a fix as early as possible, try using `master`. 

Also, please note the ArgoProj's general guidance around the use of vulnerability scanners: https://github.com/argoproj/argo-cd/security/policy

We observe a similar policy on Argo Workflows, and will update our docs soon to reflect this.

**Comment by terrytangyuan** [comment]
There were quite a few Golang version updates from dependabot but those are not included in the patch release since we only cherry-picked bug fixes: https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+golang+is%3Aclosed

**Comment by kalpanathanneeru21** [comment]
when we can expect a new release with above mentioned patches

**Comment by terrytangyuan** [comment]
See https://github.com/argoproj/argo-workflows/issues/10830

**Comment by kalpanathanneeru21** [comment]
Thanks for the immediate response. Is it possible to cut a pre release image with mentioned patches since we are using argo-workflows image.

**Comment by kalpanathanneeru21** [comment]
Tried dev-release-3.4.7. most of the vulnerabilities are solved still having few more.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/85505383/230885619-a1004ad7-6da5-48e1-b642-166ae2ef93a6.png">

**Comment by terrytangyuan** [comment]
[CVE-2023-28840: Encrypted overlay network may be unauthenticated](https://github.com/moby/moby/security/advisories/GHSA-232p-vwff-86mp)
    [CVE-2023-28841: Encrypted overlay network traffic may be unencrypted](https://github.com/moby/moby/security/advisories/GHSA-33pg-m6jh-5237)
    [CVE-2023-28842: Encrypted overlay network with a single endpoint is unauthenticated](https://github.com/moby/moby/security/advisories/GHSA-6wrf-mxfj-pf5p)
    
I'll look into those soon.

**Comment by terrytangyuan** [comment]
We can upgrade docker to `20.10.24`.

**Comment by kalpanathanneeru21** [comment]
When can we expect the release along with mentioned CVE's fix's

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/releases/tag/v3.4.7
