### ISSUE TITLE
Large LIST calls being made to Kube API server

### ISSUE THREAD

**Issue by prateekgogia** [argoproj/argo-workflows#10931]
# Summary
While debugging the load on API server and etcd instances, I found that argo workflow controller is making List calls every 1 minute and listing all the workflow objects in the clusters

![Screen Shot 2023-03-27 at 9 53 46 PM](https://user-images.githubusercontent.com/5033759/232562340-b37980e5-b6ab-4466-8cb8-57f6d97a230c.png)

What change needs making?
Can this implementation be switched to a WATCH call instead of using a List call?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Could you paste one of the the complete API endpoint URL? Do you have user agent information for those list calls?

**Comment by prateekgogia** [comment]
RequestURI - `/apis/argoproj.io/v1alpha1/workflows?labelSelector=%21workflows.argoproj.io%2Fphase%2C%21workflows.argoproj.io%2Fcontroller-instanceid&limit=200`

user agent- `workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.4.6 argo-controller`
username - `system:serviceaccount:argo:argo`

**Comment by tooptoop4** [comment]
guess its liveness https://github.com/argoproj/argo-workflows/blob/v3.4.7/workflow/controller/healthz.go#L34

**Comment by terrytangyuan** [comment]
Workaround is to remove your liveness probe or reduce the `limit` via `HEALTHZ_LIST_LIMIT`. Then the list call should be very minimal.

**Comment by prateekgogia** [comment]
Thanks so if I understand correctly, `HEALTHZ_LIST_LIMIT` can limit the number of workflow objects requested in the List API call?

**Comment by terrytangyuan** [comment]
Yes. It should reduce the load.

**Comment by prateekgogia** [comment]
Thanks for confirming, I am double checking with our etcd team because there has been some discussion around how `limit` param can also cause some excessive load. I will get back once I get an answer from etcd team.

**Comment by andrewsykim** [comment]
I experienced a similar issue with workflow controller, except it was doing large LIST requests for Pods. It seems like workflow controller is issuing periodic list requests without setting resourceVersion and with a labelSelector, which requires apiserver to fetch objects directly from etcd instead of using it's in-memory cache, generating a lot of heavy load on apiserver and etcd.

Ideally these sort of requests can use controller list/watch pattern instead of doing periodic lists, Google has some documentation around this here: https://cloud.google.com/kubernetes-engine/docs/concepts/planning-scalability#use_list_and_watch_pattern_instead_of_periodic_listing

Here's an example LIST request that was generating a lot of load, I redacted some fields that aren't relevant.
```
"HTTP" verb="LIST" URI="/api/v1/namespaces/<namespace>/pods?labelSelector=workflows.argoproj.io%2Fworkflow%3D<workflow>" latency="5.232824206s" userAgent="workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="9f79ab9c-7a82-4e6a-84ad-097534844c3b"
```

**Comment by andrewsykim** [comment]
Dug around and see that this issue has been fixed already! https://github.com/argoproj/argo-workflows/pull/4024 

I believe the version of workflow controller being used for this cluster did not include this version

**Comment by terrytangyuan** [comment]
Would you like to try a potential fix in this new image tag `dev-fix-list-load`? It will be ready once all builds finish https://github.com/argoproj/argo-workflows/actions/runs/4758024718/jobs/8455548828

**Comment by tooptoop4** [comment]
@prateekgogia did u retest?

**Comment by terrytangyuan** [comment]
I think this was fixed in one of these PRs: https://github.com/argoproj/argo-workflows/pull/11722, https://github.com/argoproj/argo-workflows/pull/9700, https://github.com/argoproj/argo-workflows/pull/12133, https://github.com/argoproj/argo-workflows/pull/11375

Feel free to re-open if you are still having issues.
