### ISSUE TITLE
Support for SSO where oauth flow is performed outside Argo workflows

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo-workflows#11181]
# Summary

We have included Argo workflows as a component in our internal platform. Our platform UI has single sign-on integration done with Keycloak. 

Users have to authenticate with keycloak while logging into our platform's UI.  Is it possible to pass on the session token cookie from the platform UI to Argo workflow?

# Use Cases

I think this would be useful whenever Argo workflow is integrated as a component in a larger platform where users would expect to do a single sign-on to the platform and access all constituent components seamlessly.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Argo [already supports SSO](https://argo-workflows.readthedocs.io/en/latest/argo-server-sso/), so this has long been doable.

> Is it possible to pass on the session token cookie from the platform UI to Argo workflow?

Currently, Argo does a token exchange with your SSO provider; it validates and authorizes your provider token, and then exchanges that for its own token. This is done because users wanted configurable expiry times and other features in the past.

There is also a feature request to re-allow the old variant of direct token usage without an exchange in #12049, which is perhaps what you're seeking?
