### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#11390]
# Summary

Adding versioning to argo-workflows docs https://argoproj.github.io/argo-workflows/

# Use Cases

When searching docs for the specific version of argo workflows you have deployed

Currently argo-cd has versioning in their documentation. Was introduced with [this PR](https://github.com/argoproj/argo-cd/pull/5099)

Would require setup and then migration/rewriting of docs to have docs split by version. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tico24** [comment]
Happy to help with the re-write. I have tried to set up versioning in the past, and failed so I need an adult to help me get that bit set up.

**Comment by caelan-io** [comment]
Tim and I just remembered why the Argo Workflows docs weren't an easy switch like it seemed it was for Argo CD's docs: Argo Workflows isn't using Readthedocs for its docs website. 

I believe this means we need to scope out a way to incorporate versioning into the mkdocs build of the Argo Workflows docs. 

Resources related to this:
- https://pypi.org/project/mkdocs-versioning/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

**Comment by agilgur5** [comment]
This would be useful for features that have yet to be released as well. Just had someone file an issue for a feature I wrote that hasn't been released yet (c.f. https://github.com/argoproj/argo-workflows/issues/11412 / https://github.com/argoproj/argo-workflows/pull/11445). Similar to how Argo CD has the `latest` version of the docs.

This gets into some complications about versioned docs that I've run into before too:
- A docs improvement or clarification can be back-ported to old docs versions
- New docs for previously undocumented features can be back-ported to old docs too (such as #11297)
- Docs about new features should be released with the feature
- Generated docs should follow the same principles

Or, in other words, SemVer applies to docs too 😅

**Comment by agilgur5** [comment]
Just jotting down here that in the previous contributor meeting ([on Aug 15th](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.qogh82i9yij0)), we discussed that moving to Read the Docs like Argo CD may be easier and more consistent than adding versioning to `mkdocs`.

Briefly mentioned redirects as well. If that is the target state, I may want to hold off adding some `mkdocs` plugins, like one for redirects as I mentioned in #11516.

Different kinds of redirects potentially. The one discussed in the meeting would be to ensure that old docs all redirect to new docs if there is a migration. The one I mentioned in the PR above is for _internal_ redirects, i.e. if we change the URL of a page, that we can add a redirect to the new page.

Redirects are very important to make sure old links to the docs continue working and don't just summarily break, causing confusion and churn in the ecosystem.

**Comment by jmeridth** [comment]
Getting started on this by setting up readthedocs.io.

**Comment by jmeridth** [comment]
@crenshaw-dev do we have a central readthedocs.io account for all argoproj accounts or do we currently have one or personal readthedocs.io accounts?  I ask, if we have one account I'd like to get access to get argo-workflows setup.  /cc @terrytangyuan

I've created my own account, username is jmeridth.  Would prefer to not setup under my account but can and maybe transfer or add other owners.

**Comment by terrytangyuan** [comment]
I don't think there is any specific project in RTD yet. Feel free to start one.

**Comment by agilgur5** [comment]
> Just jotting down here that in the previous contributor meeting ([on Aug 15th](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.qogh82i9yij0)), we discussed that moving to Read the Docs like Argo CD may be easier and more consistent than adding versioning to `mkdocs`.
> 
> Briefly mentioned redirects as well. If that is the target state, I may want to hold off adding some `mkdocs` plugins, like one for redirects as I mentioned in #11516.

Noting here that JM and I discussed this offline and we were slightly mistaken there.
Argo CD is [using](https://github.com/argoproj/argo-cd/blob/0e67ed89acac213a0dc358001d1fda2804b2d46d/mkdocs.yml) `mkdocs` for the docs _build system_ as well, but is _hosting_ docs [on](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/.readthedocs.yml) RTD, while Workflows was _hosting_ on GH Pages.

Now [CD](https://argo-cd.readthedocs.io/), [Workflows](https://argo-workflows.readthedocs.io/), and [Rollouts](https://argo-rollouts.readthedocs.io/) are all _hosted_ on RTD, just [Events](https://argoproj.github.io/argo-events/) is still leftover hosted on GH Pages and therefore doesn't have documentation versions yet.
CD and Workflows also [both](https://argoproj.github.io/argo-cd/) [redirect](https://argoproj.github.io/argo-workflows/) from their old GH Pages host to RTD. Rollouts does not have a redirect from its [old GH Pages site](https://argoproj.github.io/argo-rollouts/), so that still needs an update. Also its GH Pages site has [a versions drop-down](https://github.com/argoproj/argo-rollouts/blob/3948d01a14a5dff80f7ae4341b7e424d3de19a19/index.html#L3555), but doesn't actually support versions on GH Pages. I'll file an issue for this shortly in Rollouts.
CD, Workflows, Rollouts, and Events [are](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/mkdocs.yml) [all](https://github.com/argoproj/argo-workflows/blob/c63c2bc1838bc6069703c3cd31873b51329ce15d/mkdocs.yml) [on](https://github.com/argoproj/argo-rollouts/blob/0fab0f2afbd1e7bbd985f76e2ee73bb84a7db6de/mkdocs.yml) [the](https://github.com/argoproj/argo-events/blob/bec39df2b40ed761d2f8786b944ce70b8d22e8fc/mkdocs.yml) same docs build system, `mkdocs`, and have all been on it for as long as I know at least.

To be specific, RTD isn't a docs build system at all, it's purely a docs _host_. So I've actually been fine to add `mkdocs` plugins this whole time and so will be doing that shortly. Redirects and Mermaid support are two plugins in particular that we need.

There are still two tiny differences right now though.
One is that Workflows (and Events) doesn't have the version drop-down in the top bar of the docs, but we can probably implement that by adding the `extra_css` and `extra_js` that [CD](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/mkdocs.yml#L5) and Rollouts have for a `versions.css` and `versions.js` file. Would be good to add for consistency once we properly backport some versions of the docs.
The other is that CD and Rollouts use a sidebar for all sections and no topbar tabs what-so-ever.  Workflows and Events both have topbar tabs. We may want to move to doing the same as CD or vice-versa. (My memory might be wrong here, but I could've sworn CD used to have topbar tabs too and then changed from that at some point in time, as I vaguely remember being disoriented at CD's docs one day in the past. Will add a link to a PR there if I can find one and that actually happened 😅)

**Comment by agilgur5** [comment]
> * Would be good to add for consistency once we properly backport some versions of the docs. Right now we have the little floating bottom version overlay button instead (seems to be the RTD default?)

Update: RTD has made this a good bit bigger now: 
![Screenshot 2024-03-19 at 1 55 30 PM](https://github.com/argoproj/argo-workflows/assets/4970083/e4196101-abfd-4c23-b361-af8cc2f9e39b)

And added its own warning about `latest` vs. `stable` docs: ![Screenshot 2024-03-19 at 1 55 38 PM](https://github.com/argoproj/argo-workflows/assets/4970083/4fe25699-6b76-4846-9fbc-eeeb47cd84b0)

Seems to have rolled out sometime in the past few days.

> * We can probably implement that by adding the `extra_css` and `extra_js` that [CD](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/mkdocs.yml#L5) and [Rollouts](https://github.com/argoproj/argo-rollouts/blob/0fab0f2afbd1e7bbd985f76e2ee73bb84a7db6de/mkdocs.yml#L5) have for a `versions.css` and `versions.js` files.

So part of this is no longer necessary. These scripts also tend to break when RTD updates, so perhaps being consistent with RTD and letting it do its own thing makes more sense, and maybe CD should remove their customization 🤷 .

For instance, right now there's a duplicate version drop-down in CD at the bottom of the page: 
![Screenshot 2024-03-19 at 1 59 03 PM](https://github.com/argoproj/argo-workflows/assets/4970083/aad458b5-0d53-4d00-9dad-4ad5cc26431e)

And previously: https://github.com/argoproj/argo-cd/issues/11999, https://github.com/argoproj/argo-cd/pull/13102, etc
