### ISSUE TITLE
UI: `links` for label containing dot not working

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11741]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

using links: in wfcontroller configmap:

for a label key not containing slash it works, ie this works:
```label=s3-folder%3D${workflow.metadata.labels.s3-folder}```

for a label key containing dot slash it returns null in the generated link url:
```label=workflows.argoproj.io%2Fworkflow-template%3D${workflow.metadata.labels.workflows.argoproj.io/workflow-template}```
below also returns null
```label=workflows.argoproj.io%2Fworkflow-template%3D${workflow.metadata.labels.workflows.argoproj.io%2Fworkflow-template}```

### Version

3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
If this is a UI-only error, [this function](https://github.com/argoproj/argo-workflows/blob/8e01696a9c63f25b3660ed479c6f7a57bb61d82d/ui/src/app/shared/components/links.tsx#L24) may need updating to handle this.

Is it slashes specifically that fail, or the fact that the label has dots in it?
[This line](https://github.com/argoproj/argo-workflows/blob/8e01696a9c63f25b3660ed479c6f7a57bb61d82d/docs/workflow-controller-configmap.yaml#L82) in the example configmap works, but that's a static link, not a templated link

**Comment by tooptoop4** [comment]
my guess is that it doesn't know how to reference label key with dot because it might be searching for a key of 'workflows'

**Comment by agilgur5** [comment]
Yea it's definitely the dot. It's used as a [delimiter](https://github.com/argoproj/argo-workflows/blob/8e01696a9c63f25b3660ed479c6f7a57bb61d82d/ui/src/app/shared/components/links.tsx#L29). The slash shouldn't matter since it uses [bracket notation](https://github.com/argoproj/argo-workflows/blob/8e01696a9c63f25b3660ed479c6f7a57bb61d82d/ui/src/app/shared/components/links.tsx#L31).

This would need a more complicated regex to solve. Either the user input would have to be in bracket notation or could specifically check for labels and annotations and stop delimiting at the end. Bracket notation would be more consistent with `expr` on the backend and JS bracket notation, so I'd probably opt for that.
We'd need a new example for the docs of this as well. And tests would be good to have too.

**Comment by tooptoop4** [comment]
i tried bracket notation but still no luck

**Comment by agilgur5** [comment]
Correct, it is not currently supported. That was just one option / proposal I wrote if a fix were to be implemented.

**Comment by agilgur5** [comment]
Oh right, figured I'd mention that the workaround would be to not use a dot in the label.

**Comment by tooptoop4** [comment]
maybe https://github.com/argoproj/argo-workflows/pull/13752 will help

**Comment by BojanZelic** [comment]
it seems like with the merged PR there would still be an issue getting labels/annotations from `podMetadata`

ex: 
```
${workflow.spec.podMetadata.annotations.workflows.argoproj.io/something}
```

wouldn't work because the logic is only limited to `workflow.metadata.labels` or `workflow.metadata.annotations`
