### ISSUE TITLE
Remove mentoring docs/issue template

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11802]
I am considering removing the mentoring option and related docs going forward. Any objections?

Reasons:
* We got a lot of mentoring requests and do not have many active mentors.
* They often become stale and frustrate new contributors.
* We should encourage people to comment on existing issues that they are interested in working on.

**Comment by agilgur5** [comment]
> * We got a lot of mentoring requests and do not have many active mentors.
> * They often become stale and frustrate new contributors.

As mentioned over Slack, I'm for this as I think the current implementation / execution actually gives a bad impression and has the opposite of its intended effect, making people _less_ likely to contribute. Given the docs and templates (and their wording), the "mentoring program" _sounds_ very robust and it seems like a mentor could potentially dedicate a lot of time to a mentee (especially when mentioning sync calls etc).

But given the lack of people able and willing to mentor compared to the amount of mentoring requests, I think this gives a false impression. Or, putting it another way, it feels misleading. Stalebot is already [not well liked](https://drewdevault.com/2021/10/26/stalebot.html) in OSS (including by me, but that is a separate topic), and having stalebot further mark your mentoring as stale when you never even got a response could feel extremely frustrating, disappointing, and even agitating. 

In my opinion, I think it's better to not have a mentoring program than have a misleading one that has the opposite effect of its original intentions. In some cases, it also creates a bottleneck as able contributors file a mentoring request and wait for a response (that never comes) instead of making a draft PR or responding to an issue (with questions that could potentially help other interested community members) etc.
Perhaps it was more viable in the past, but right now, I am surprised it exists given that so many requests are marked as stale. I've never filed a mentoring request myself, but it frustrates and disappoints me as well to see that. And when I respond to an old mentoring request about an issue I stumbled upon, I am apologizing that their request was never responded to timely (even though their request and the program pre-date me).
At the very least, I think it would be good to narrow the scope of the program (perhaps significantly).

As a point of reference, Argo CD [does not have a "mentoring program"](https://cloud-native.slack.com/archives/C020XM04CUW/p1692625660746069?thread_ts=1692599497.512039&cid=C020XM04CUW) despite having more contributors and more interested community members.

> * We should encourage people to comment on existing issues that they are interested in working on.

I think most mentors already do this anyway (including me), so one option would be to more explicitly document this and more clearly communicate that draft PRs and clarifying questions on issues and PRs are totally fine (there is still a bit of a PR backlog though).

Along those lines, one option would be to redirect the mentoring template to a docs page that explains how one can ask for help and interact with issues and PRs. The mentoring docs page can be rewritten to match that representation.

**Comment by terrytangyuan** [comment]
That's another topic. Do you have any alternative proposal that works better than stalebot?

**Comment by agilgur5** [comment]
It is a separate topic, that's why I didn't really go into it in my first comment. Per the [linked blog post](https://drewdevault.com/2021/10/26/stalebot.html) I shared above (which I actually found from a comment in an issue here I believe), yea can just remove it entirely. 

Here's a few hypothetical scenarios:
1. There's a bug
    1. It's not fixed. There's no point in closing it as stale.
    1. It's fixed. It should be closed regardless of stale or not.
1. There's a feature.
    1. It's not implemented nor rejected. It should not be closed as stale.
    1. It's either implemented or rejected. It should be closed regardless of stale or not.
1. There's a PR.
    1. It hasn't gotten a response or is awaiting review/merge. It should not be closed as stale.
    1. It's gotten a response and needs more work. This can be marked as stale and eventually closed out if there is no further work done.
1. There's something else (e.g. the [very recent](https://cloud-native.slack.com/archives/C0510EUH90V/p1694306229387299?thread_ts=1692642013.912419&cid=C0510EUH90V) support label, or the mentoring label in the past).
    1. It's hasn't been answered or responded to. It should not be closed as stale.
    1. It has been answered or responded to sufficiently. It should be closed regardless of stale or not.
    1. It has been answered partially, but needs more information. This can be marked as stale and eventually closed out if there is no further response from the author.
    
So out of 9+ possible scenarios, only 2 of them is really appropriate to be closed out as stale (IMO).
I don't use stalebot in other repos I maintain either.

Also, as another reference, I have quite literally been going through _dozens_ of bugs in this repo that were marked as stale and closed, removing the label if it were actually properly closed out (which is many) and referencing the PR that closed it. Those that were just closed as stale and never fixed may actually still be active bugs.
I've gone through stale PRs as well and plan to revive some of them when I have some time.
I've done the same in `argo-ui` as well. Still got more to go in both repos.
