### ISSUE TITLE
UI: Optional field to hide WorkflowTemplate

### ISSUE THREAD

**Issue by SachinChauhan1302** [argoproj/argo-workflows#11822]
# Summary

Sometimes we need a main workflow that calls many others sub workflow templates under the hood.
Currently the Argo workflow UI shows all of the WorkflowTemplate definitions in the UI. 
Is there a possibility as a feature to annotate in the definition or an optional field that dictates this behaviour for Argo UI.
This helps to keep the UI uncluttered.

## Use Cases

Generally application developers don't create workflows in big organizations and Workflow templates are created by other DevOps/Ops teams for app developers to consume. It would help to only expose top level workflows in the UI for the App Developers to consume.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by SachinChauhan1302** [comment]
An example annotation can be as follows while defining the `WorkflowTemplate` CRD, which Argo UI server can read to manage display of workflow templates or any feature on similar lines.

```
kind: WorkflowTemplate
metadata:
  annotations:
      argoproj.io/visible-in-ui: False
```

**Comment by agilgur5** [comment]
So there is a label filter available already that you can use. You can also use the [custom links feature](https://argoproj.github.io/argo-workflows/links/) to provide a button directly for that query.

Implementing the feature as you propose would not be very difficult, but as with all UI-specific limitations, a really important note is that users could still use those WorkflowTemplates via the API. A UI filter like this would make them "not visible", but if the user has RBAC to access those, they will still be able to access them through the API.

You may be able to limit your users with the existing k8s RBAC right now, for instance, via a `resourceNames` allowlist. Otherwise a more granular RBAC approach would require something like Casbin #6490.

**Comment by agilgur5** [comment]
Question: would you want this filter in the CLI as well? Or a separate label/annotation for the CLI?
As ideally we keep the UI and CLI UX similar (it tends to be confusing when they function differently)

Also mentioned this in a related [Argo CD thread on Slack](https://cloud-native.slack.com/archives/C020XM04CUW/p1695154393673099?thread_ts=1695147678.995079&cid=C020XM04CUW) today.

**Comment by SachinChauhan1302** [comment]
Although main aim is to unclutter the UI space, It is good to have a feature parity.
`argo template list` can have a flag like `--show-all` to show all workflows irrespective of the annotations and inline with the `kubectl get WorkflowTemplates`

**Comment by agilgur5** [comment]
This seems to have been a duplicate of #7326
