### ISSUE TITLE
Support Github Action Workflows as argo workflow templates

### ISSUE THREAD

**Issue by andyleap** [argoproj/argo-workflows#11824]
# Summary

Github Actions Workflows (GHA Workflows) are a simple way to allow developers to easily run code from a repo.  Argo Workflows has great orchestration features.  We could use the best of both worlds by allowing you to run a GHA workflow as a single node in an Argo workflow.

## Use Cases

When would you use this?

Longer term deploys:  A phased deploy that does

- Build Image
- Deploy Canary
- Wait 1 day
- Deploy Prod

is technically possible with raw github, but when you start getting more complex, stuff starts breaking down, i.e. if you want to have that 1 day wait and then poke someone to say "Are we okay to continue", you'd have to start building additional tooling or complex enviroment based workarounds.  With Argo Workflows, it could be as simple as

- Build & deploy canary GHA workflow
- 1 Day suspend node
- Hermes slack notification & suspend node (user would go in and resume the suspend node if they are good with proceeding)
- Deploy Prod GHA workflow

## Alternatives

- Executor Plugin
  This could obviously be written as an executor plugin, and I'm interested in doing so, but wanted to bring up the possibility of integrating this in the main project as well
- Simple binary
  We do this currently, a binary that runs the workflow inside argo workflows, but there's obviously extra complexity and mismatches around inputs/outputs and status stuff that could be improved.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
So from the title I thought you might mean an integration that converts an GHA DAG to an Argo DAG, or something like that. There are some existing issues and prior work on things like CWL (Common Workflow Language) and Kubeflow Pipelines, so that would fit into a similar scope.

But reading the issue, it sounds like you want something a bit different, that seems already possible as far as I can tell.

> run a GHA workflow as a single node in an Argo workflow.

You mentioned a "simple binary" further, so it sounds like you have this working already? I would think that this would already be possible with [`act`](https://github.com/nektos/act) or something.

Although based on the rest of the issue, I'm not sure if you mean "run" as in "execute on the same hardware" or "call an API".

> you'd have to start building additional tooling or complex enviroment [sic] based workarounds. With Argo Workflows, it could be as simple as: 

This sounds like a pure API integration? You should be able to call the GH API with a `container`, a `script`, or an `http` template.

Not sure if you meant something different.

> but wanted to bring up the possibility of integrating this in the main project as well

I'm only a single contributor, but I would be against this. It has tight coupling to a very specific provider, which does not align well with Unix philosophy. If a user-level wrapper can do this, that sounds like a good place for it. It could potentially even be hosted in [`argoproj-labs`](https://github.com/argoproj-labs) too, where there are a good amount of community projects (like the actively maintained [Hera SDK](https://github.com/argoproj-labs/hera) for Workflows).

**Comment by andyleap** [comment]
> > run a GHA workflow as a single node in an Argo workflow.
> 
> You mentioned a "simple binary" further, so it sounds like you have this working already? I would think that this would already be possible with [`act`](https://github.com/nektos/act) or something.

Yeah, I'm looking at running github actions on github directly, not locally.  And yes, we do already have this working, but the UX is poor, and writing out the templates is not clean or ideal

> > you'd have to start building additional tooling or complex enviroment [sic] based workarounds. With Argo Workflows, it could be as simple as:
> 
> This sounds like a pure API integration? You should be able to call the GH API with a `container`, a `script`, or an `http` template.
> 
> Not sure if you meant something different?

Nope, this is a pretty simple integration, though a little more then just an http template to make it work well :D

> > but wanted to bring up the possibility of integrating this in the main project as well
> 
> I'm only a single contributor, but I would be against this. It has tight coupling to a very specific provider, which does not align well with Unix philosophy. If a user-level wrapper can do this, that sounds like a good place for it. It could potentially even be hosted in [`argoproj-labs`](https://github.com/argoproj-labs) too, where there are a good amount of community projects (like the actively maintained [Hera SDK](https://github.com/argoproj-labs/hera) for Workflows).

Would be open to making this more of a generic thing with pluggable providers or using it as a source of data for improvements to the plugin system.

**Comment by agilgur5** [comment]
> And yes, we do already have this working, but the UX is poor, and writing out the templates is not clean or ideal

Could you provide some examples? I think those would be very helpful context for an issue and make it more concrete

**Comment by agilgur5** [comment]
So we recently rejected a MongoDB template in https://github.com/argoproj/argo-workflows/pull/11842#issuecomment-1726068298 to instead prefer a plugin for it, so I think this would fall under the same scope.

@terrytangyuan do you want to give final decision on that and close as not planned?

**Comment by terrytangyuan** [comment]
Are you looking for something like https://github.com/marketplace/actions/submit-argo-workflows-from-github?

**Comment by agilgur5** [comment]
@terrytangyuan per the thread, I believe they were looking for the other way around -- submit GH Action from Argo, in a cleaner way than with an `http` template.

**Comment by terrytangyuan** [comment]
I don't think we'll support that. A plug-in or http template should work.
