### ISSUE TITLE
Improve confirmation prompt message

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11905]
When deleting a selected workflow in the workflow list view, we get a confirmation prompt to check whether to delete the workflow in the database. Currently, the checkbox says "don't allow...to prompt you again" but it should be a "yes". 

![image](https://github.com/argoproj/argo-workflows/assets/4269898/eb3af3d6-89be-459d-bf5e-bb38d2cada1a)
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
> Currently, the checkbox says "don't allow...to prompt you again" but it should be a "yes".

I think you're misunderstanding this. This checkbox is from the browser itself and is not something that can be changed.
`confirm` is a [browser API](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm). Checking that box means that the website will no longer be able to send you prompts through that method. You actually _don't_ want to check that.

`confirm` is synchronous and blocks the main thread and is not very customizable, so HTML modals have become preferred over this method (particularly since HTML5 -- over a decade). I'm guessing browsers have seen some abuse of these methods, so they can be suppressed in some browsers, similar to how downloads can be suppressed (or location access or notifications can be suppressed -- i.e. many browser APIs nowadays).

`argo-ui` already has the `PopupApi` to use instead of these browser APIs and it is available in [the context](https://github.com/argoproj/argo-workflows/blob/22d8461baec5978e7214c9a444ae62a3ae9e618f/ui/src/app/shared/context.ts#L8).
So this ticket should be rewritten to change the prompt from using `confirm` to using `popup.confirm`. Can see an example of that [here](https://github.com/argoproj/argo-workflows/blob/e91c2737f3dff1fee41ce97991e294a57c53fc93/ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx#L114) -- although that should be updated to use async/await as per #11740. `popup.confirm` is an async method that creates an HTML modal.

The change is not very difficult, but as it does rely on some internal libraries, I'm not sure that I would label this as a "good first issue".

**Comment by agilgur5** [comment]
> I'm guessing browsers have seen some abuse of these methods, so they can be suppressed in some browsers

Ah, I see, there's two `confirm`s in a row used [here](https://github.com/argoproj/argo-workflows/blob/e91c2737f3dff1fee41ce97991e294a57c53fc93/ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx#L51), so the browser interprets this as possible abuse.

**Comment by agilgur5** [comment]
I'm just gonna update this myself as I'm starting at the code right now anyway and this is not that straightforward an issue

**Comment by terrytangyuan** [comment]
Sounds good.

**Comment by terrytangyuan** [comment]
Yea I understand it's not customizable and we should switch to use PopupApi like I did in WorkflowDetails page.
