### ISSUE TITLE
Proposal: Separation of Execution Authority for Workflows using WorkflowTemplate

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12086]
# Summary

I think it is better to have separate permissions for executing Workflows that use WorkflowTemplate and for executing new Workflows.
Some people (not developers) will only run Workflows that use WorkflowTemplate on a regular basis,
In many cases, there is no need to be able to execute other Workflows.

## Use Cases

- Use when you do not want arbitrary code to be executed.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
There is the [Workflow Restrictions](https://argoproj.github.io/argo-workflows/workflow-restrictions/) feature that does exactly this -- it only allows users to run Workflows that use a `workflowTemplateRef`.

This can't be set on a per-user level though, since Argo's authZ model uses k8s RBAC, and this is outside of k8s RBAC. #6490 could cover this.

Or you could use a policy engine to make such decisions on a per-user level.

**Comment by panicboat** [comment]
Workflow Restrictions is what we needed, thank you!
