### ISSUE TITLE
Output log of track UI event when workflow is submitted

### ISSUE THREAD

**Issue by kosukeoya** [argoproj/argo-workflows#12081]
# Summary

Output log of track UI event when workflow is submitted.

Specifically, we would like to track the following cases
- Workflow resubmit
- Workflow submit from WorkflowTemplate
- Submit CronWorkflow

Additionally, it would be nice to be able to track the name of the workflow as well.

## Use Cases

It can serve as an audit log by recording who performed which workflows.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tooptoop4** [comment]
dupe of https://github.com/argoproj/argo-workflows/issues/4271 and https://github.com/argoproj/argo-workflows/issues/10257

**Comment by agilgur5** [comment]
> dupe of #4271 and #10257

ostensibly yes, those should support some method of an immutable log of events server-side. 

That's not exactly the same of the title of this issue, which is on UI events sent to the API. Notably, those are spoofable and easily skippable as they are client-side in the browser and so should not be relied upon in general. Whereas server-side events effectively require cluster-admin to spoof (at which point, it's not necessarily considered a spoof at all).

> It can serve as an audit log by recording who performed which workflows.

The description does say "audit log" though, so I think the _intent_ of this issue is correctly covered by those, so marking as duplicate as such.
