### ISSUE TITLE
UI: 3.5 missing name + name prefix filters for archived workflows

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#12161]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

v3.4.11 had 'name' and 'name prefix' filters in the 'archived workflows' ui, this is extremely useful to filter on workflows starting with a name or an exact name. particularly if its a sensor generated workflow or you just want to jump to a known workflow name without needing to construct a url in the browser address bar (not user friendly)

v3.5.1 has no such option in the UI!

### Version

3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by maxisam** [comment]
We also need a filter for archive items. We didn't need it because It was a separated view.

**Comment by agilgur5** [comment]
### doable now

This is now doable with the SQLite DB from #13021 / #12736. It previously was not possible for non-archived Workflows as k8s/etcd has no such native filter per https://github.com/argoproj/argo-workflows/issues/12025#issuecomment-1914065370

### implementation details; naming

#### archived vs. non-archived filter

@Adrien-D "State" is a bit ambiguous naming; that part we did actually discuss this in https://github.com/argoproj/argo-workflows/issues/12025#issuecomment-1865458377 et al, where I suggested "Workflow Storage" and "In-cluster" vs. "Archived" as the options. "Active" is a bit ambiguous as well, as was the original terminology of "Live" workflows.
To be fair, you can have an Archive DB in your cluster too, so "In-cluster" is not necessarily fully precise either, but "etcd" is an implementation detail of k8s and so could be both confusing and imprecise on some distros as well. "k8s resources" sounds a bit confusing user-side as well 😕 

Ideally also the checkboxes shouldn't display if you don't have the Workflow Archive enabled.

Also, this requires adding a new option to the API method, it is not a UI-only change, as I learned in https://github.com/argoproj/argo-workflows/issues/12025#issuecomment-1914065370 and others in #12237. The API implementation should roughly follow https://github.com/argoproj/argo-workflows/pull/12237#discussion_r1433459929

#### name filter

That one looks good to me, I like it. Seems more efficient than the original in #6801 as well

**Comment by Adrien-D** [comment]
@agilgur5 I see the confusion with "State" and "Active", I'm not very familiar with all of this wording (and this repo yet) so thanks for giving me some details, helps a lot !
"Workflow Storage" "Unarchived" + "Archived" is good for me, it's indeed the less confusing

For the implementation details I'm trying to understand what you're saying. I did some work [here](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows) on name filter (Didn't start the archived filtering yet) so maybe it can be a good start to discuss my understanding of the implementation

I'm already facing some issues that I need to understand for consistency :
- Why for workflow templates do we have `NamePattern` as it's own a query parameter instead of a listOptions ? Should I implement it as it's own query parameters as well ? [See here](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-541631b3bd9f443103173fe1eadef58d0fcde07aa75c09b3de38b7e31e651845L16)
- Why for `ListWorkflows`, `CountWorkflows` are we [forwarding namePrefix ](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-4a9417b41e56ae4eca8b3f57b09c55d93061913aa07fd02a82c47c1fadf3ee0eL13) as it looks like it's none even used [[1]](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-d02453af864e8270f89b0149c31588ac3871ae051f67c1f5178ac6f0ef3fa38fL132) [[2]](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-d02453af864e8270f89b0149c31588ac3871ae051f67c1f5178ac6f0ef3fa38fL137)
- Why for `CanI` are we forwarding "Name" as[ we don't seem to use it](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-784bce82e86d0fc94704b79d2d428e3c69a73a5f1e070f0071e2e01ecd21de2fL12) ?

For the UI I inspired from grafana's interface as they have a good UX on filter in my opinion, hopefully the down arrow will help to understand that the field is clickable

**Comment by agilgur5** [comment]
> * Why for workflow templates do we have `NamePattern` as it's own a query parameter instead of a listOptions ? Should I implement it as it's own query parameters as well ? [See here](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-541631b3bd9f443103173fe1eadef58d0fcde07aa75c09b3de38b7e31e651845L16)

I believe that's because it's using k8s's `metav1.ListOptions` as the type, not `ListOptions`, no?



> * Why for `CanI` are we forwarding "Name" as[ we don't seem to use it](https://github.com/argoproj/argo-workflows/compare/main...Adrien-D:name-search-workflows?expand=1#diff-784bce82e86d0fc94704b79d2d428e3c69a73a5f1e070f0071e2e01ecd21de2fL12) ?

That actually might be a mistake; it used to be used prior to #2670 as [this line](https://github.com/argoproj/argo-workflows/pull/2670/files#diff-10789fdfe9fcd47b01b89c63b756fa92802e56ce0cd545b4df4bce1b2f2e8a07L21) was removed in the refactor. This would only make a difference when `resourceNames` is used if I'm understanding correctly, so it may have just happened to work fine in most cases. But I'm not 100% sure if that's exactly how it works, I don't think I've ever tried with a specific `name`.

**Comment by Adrien-D** [comment]
@jiachengxu @agilgur5 Thanks for your answers. I implemented your feedback on my PR https://github.com/argoproj/argo-workflows/pull/13160

I'll make the filtering archived/non-archived WF on a separate PR to make the review easier.

**Comment by agilgur5** [comment]
> I'll make the filtering archived/non-archived WF on a separate PR to make the review easier.

Let's split that out into a separate issue as well and link back to here for reference. This issue does not include it in its title and we have #13151 for native date filtering already as well.

**Comment by Adrien-D** [comment]
Archive filtering will be done in this issue https://github.com/argoproj/argo-workflows/issues/13171
