### ISSUE TITLE
default view is warning about 500 succeeded workflows

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#12160]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

after upgrading to v3.5.1 the workflows page shows warning about 500 succeeded workflows

### Version

3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
> after upgrading to v3.5.1 the workflows page shows warning about 500 succeeded workflows

I'm not sure what you're referring to. You didn't provide any details beyond this. I personally haven't seen this warning before.

We would also need details as to why this behavior is a "bug" and why it is incorrect behavior. Something new or different is not necessarily buggy.

Same as I wrote in one of your other issues: In general, more details are almost always better than few details, which is why they are asked for in issue templates. A one-liner generally does not help much with diagnosis. See also https://stackoverflow.com/help/how-to-ask, https://stackoverflow.com/help/minimal-reproducible-example

**Comment by agilgur5** [comment]
The only thing I can think you were referring to you is the [Cost Optimization nudge](https://github.com/argoproj/argo-workflows/blob/80cd2ec6cffa5e33f8cce67435ba96e68a2a32b4/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L232) that says: "You have at least {counts.incomplete} incomplete, and {counts.complete} complete workflows. Reducing these amounts will reduce your costs.".

That nudge only appears if you have >100 of either incomplete or complete Workflows. It's existed for at least 3 years since Argo v2.9 as well (added by #3089) and has not changed since

**Comment by tooptoop4** [comment]
that sounds like the message but 3.4.11 was NOT affected as workflows UI would only show unarchived (which had less than 500) and the archived UI did not show this message. but with 3.5.1 having both together it shows, which is another alert for users to worry about

**Comment by agilgur5** [comment]
Ah, I see, yea that seems like an oversight on the implementation of the unified Live + Archived API. The API was changed but not the UI.

I'll need to check the old Archived UI, but I don't think Archived Workflows were meant to be included in that count, since it's about GC, which is primarily about etcd, not about the Archive DB (although that too could be cost optimized)
