### ISSUE TITLE
Failed to load version/info Error: {"code":16,"message":"token not valid.. with SSO setup

### ISSUE THREAD

**Issue by atropos112** [argoproj/argo-workflows#12168]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Open a website for argo-workflows and not see

```
Failed to load version/info Error: {"code":16,"message":"token not valid. see https://argoproj.github.io/argo-workflows/faq/"}
```

before doing anything.

To be clear, SSO login works, but the error message appearing every time appears troublesome.

### Version

3.5.1 and latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
1. Install argo-workflows
2. Use sso via sso argument using the community helm chart (i dont think it being a chart is relevant here)
3. Open the website

The steps above are what got me here, I suspect there is something else going on that is causing this though?
```

### Logs from the workflow controller

```text
time="2023-11-08T16:57:41.079Z" level=debug msg="received config map argo-events/argo-events-controller update"
time="2023-11-08T16:57:43.114Z" level=debug msg="received config map argo-events/argo-events-controller update"
time="2023-11-08T16:57:45.151Z" level=debug msg="received config map argo-events/argo-events-controller update"
time="2023-11-08T16:57:45.620Z" level=debug msg="Get leases 200"
time="2023-11-08T16:57:45.632Z" level=debug msg="Update leases 200"
time="2023-11-08T16:57:47.201Z" level=debug msg="received config map argo-events/argo-events-controller update"
time="2023-11-08T16:57:49.263Z" level=debug msg="received config map argo-events/argo-events-controller update"

adding them for completeness, i don't think anything there is applicable here sadly
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by agilgur5** [comment]
> To be clear, SSO login works, but the error message appearing every time appears troublesome.

This isn't a bug, this is an error message you're getting before logging in or when having a no longer valid token.

Depending on your configuration, not all information is available to logged out users. The Argo version, the user's info, UI customizations, etc are some of those that are unavailable.

**Comment by atropos112** [comment]
Imagine you go on google.com and get a big popup telling you "You can't check your e-mail" (which as it would turn out is because you are not logged in) wouldn't you classify this as a bug ?

What you are suggesting is that I as a user am using the application correctly this would suggest this is not a user error, because user caused no error. And if its not a user error then its a server error, and if its a server error then in this circumstance its a bug. 

Beside arguing if its a bug or not, why is it even bothering to tell me that I can't see version, just don't show me the version until I log in problem solved.

**Comment by agilgur5** [comment]
> Imagine you go on google.com and get a big popup telling you "You can't check your e-mail" (which as it would turn out is because you are not logged in) wouldn't you classify this as a bug ?

I think you mean `gmail.com` in this case, which is more innocuous than `google.com` as it requires logging in. It's also a toast notification in the bottom right corner of the screen, not a "big popup", which is similarly more innocuous. That is a bit of an extreme comparison as written.

There are indeed websites that give you a "token invalid" notification while kicking you back to the login screen, which this is the equivalent of. Maybe Gmail doesn't, but there are other websites that do.

I didn't think that notification was a bug when I saw it. But I think right now it is a catch-all message which is perhaps the more specifically confusing part, as correct behavior shouldn't point you to the FAQ. Would a plain "token not valid" message be confusing or indicative of incorrect behavior?

I added the FAQ link there (as requested by the longest contributor/maintainer) in #11300 as the message was actually even _more_ ambiguous and confusing before then: "token not valid for running mode". There are some very common misconfigurations that that both of those error messages were written to address (and were written well before my time as a contributor) though, so to improve this we would have to attempt to distinguish between a misconfiguration and a plain invalid token, which is correct behavior. I'm not actually sure if that's entirely possible, which may be the original rationale behind the catch-all.

> What you are suggesting is that I as a user am using the application correctly this would suggest this is not a user error, because user caused no error. And if its not a user error then its a server error, and if its a server error then in this circumstance its a bug.

A notification does not necessarily mean that someone did something wrong. It can just be, well, a notification; in this case telling you why you were kicked back to the login screen, because your token is no longer valid.
I see the code is currently showing [`NotifcationType.Error`](https://github.com/argoproj/argo-workflows/blob/80cd2ec6cffa5e33f8cce67435ba96e68a2a32b4/ui/src/app/app-router.tsx#L55) instead of `NotificationType.Warning` though, which would perhaps be more correct.

That notification is at least ~3 years old though and has existed since at least Argo 2.x, so it's not from a recent change or anything.

> Beside arguing if its a bug or not, why is it even bothering to tell me that I can't see version, just don't show me the version until I log in problem solved.

It's not just the version, as I wrote in my previous comment. The Argo Server can also be configured with different [auth modes](https://argoproj.github.io/argo-workflows/argo-server-auth-mode/). Some do show information to logged out users (`--auth-mode=server` is practically the equivalent of no auth, as it just uses the Server's SA).

> just don't show me [...] until I log in problem solved.

This part and/or the message itself I agree are not necessarily ideal behaviors. I wouldn't call those bugs per se, as they are not _incorrect_ behavior, but are perhaps _confusing_ behavior.

It stems from [the root router code](https://github.com/argoproj/argo-workflows/blob/80cd2ec6cffa5e33f8cce67435ba96e68a2a32b4/ui/src/app/app-router.tsx#L63), as it makes requests on every page -- including the login page -- and also seems to continue to request information even if login fails.

We can perhaps skip that on the login page specifically, although that doesn't quite solve the issue of detecting a misconfiguration vs a plain invalid token 😕

**Comment by agilgur5** [comment]
> There are some very common misconfigurations that that both of those error messages were written to address (and were written well before my time as a contributor) though, so to improve this we would have to attempt to distinguish between a misconfiguration and a plain invalid token, which is correct behavior.
> I'm not actually sure if that's entirely possible, which may be the original rationale behind the catch-all.

Noting in this issue that OP suggested in https://github.com/argoproj/argo-workflows/discussions/12070#discussioncomment-7516143 to use a console warning for this, which is a potential option to resolve this piece. "invalid token" notification in the UI itself, debugging information in the browser console. As I noted there though, an Argo operator may not necessarily even know to check the browser console though, so that is not necessarily ideal either 😕

**Comment by atropos112** [comment]
I have read your responses carefully, thank you for your careful consideration i appreciate it a lot. In interest of keeping it to one subject I will close this and continue in #12070

**Comment by atropos112** [comment]
I have read your responses carefully, thank you for your careful consideration i appreciate it a lot. In interest of keeping it to one subject I will close this and continue in #12070

**Comment by agilgur5** [comment]
> This is also duplicative of #12070

Actually it turns out those are both duplicative of an older issue: #7921
Somewhat problematically, without #8179, you can't necessarily tell which auth mode you're using on the front-end.

> It stems from [the root router code](https://github.com/argoproj/argo-workflows/blob/80cd2ec6cffa5e33f8cce67435ba96e68a2a32b4/ui/src/app/app-router.tsx#L63), as it makes requests on every page

Since that happens on first page load on any page (auth check), it's hard to tell whether you tried logging and failed or didn't try logging in at all yet.

We might be able to workaround that with some cookie introspection (the cookie is an indicator you tried logging in), but in the SSO case, the cookie is currently encrypted. And during failed SSO login, you might not have gotten a cookie at all, or have an expired or otherwise unauthorized cookie.

I think we'd have to detect any possible [SSO 401 from the redirect](https://github.com/argoproj/argo-workflows/blob/52cca7e079a4f6d76db303ac550b1876e51b3865/server/auth/sso/sso.go#L258) to know that it was an unsuccessful SSO login attempt

**Comment by agilgur5** [comment]
> We might be able to workaround that with some cookie introspection (the cookie is an indicator you tried logging in)

See WIP draft PR: #13372
