### ISSUE TITLE
UI: Support markdown in CronWorkflow/WorkflowTemplate title/description

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12644]
# Summary

I would like to use markdowns not only in the Workflow list, but also in the CronWorkflow / WorkflowTemplate list.

## Use Cases

We want to have the title read as a reminder before executing a workflow.
Also, we want to have flexibility in displaying titles.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by panicboat** [comment]
Can I work on this problem?
Looks good as a Good First Issue.

**Comment by agilgur5** [comment]
I would start with plain title & description (like #9805) and _then_ add markdown, as that is more complex and has some performance ramifications due to the new deps, per my review https://github.com/argoproj/argo-workflows/pull/10553#pullrequestreview-1799370952. 

The resulting code from my modifications in #12580 is a lot more optimized, as well as fixes several bugs from the original PR.

Otherwise I think you can take this one as it is indeed fairly straightforward

**Comment by agilgur5** [comment]
Non-markdown was complete for CronWorkflows in #12674, re-opening to continue for markdown and for WorkflowTemplates
