### ISSUE TITLE
Enable draft GHSAs

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#12745]
https://github.com/argoproj/argo-cd/blob/a4b50515381bad9d6db316d49d33efae351c6222/SECURITY.md?plain=1#L68

**Comment by agilgur5** [comment]
Noting that this is from [today's Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.9ogkxyklinsn), quoted from me, which itself was a follow-up from the [SIG Security meeting last week](https://docs.google.com/document/d/1nl1adCRf4tD87Y01i3JcrLcHvtm1O5a7slqzNstct94/edit#heading=h.tmeeqc3bb4md).

To close this out:
1. Enable draft GHSAs on the repo, use the same template as CD -- this requires a repo admin (I do not have permissions to do this, which is why I brought it up)
1. Add a link to create draft GHSAs to the `SECURITY.md`, same as the CD link above (I can do this)
1. Add any folks who need access to relevant GHSAs (could be manual per GHSA if desired)

**Comment by terrytangyuan** [comment]
enabled

**Comment by agilgur5** [comment]
Thanks Terry, can you also review the security docs changes in #12747 now that it is enabled?
