### ISSUE TITLE
Security Disclosure

### ISSUE THREAD

**Issue by aydinnyunus** [argoproj/argo-workflows#12796]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I have reported the issue via email and HackerOne, in accordance with the security policy, but I have not received any response.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
I have reported the issue via email and HackerOne, in accordance with the security policy, but I have not received any response.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Hmm I don't have access to either of those (I'm actually not sure who does exactly), but I can check with some SIG Security folks. It's possible it just may not have been triaged yet (KubeCon is next week so some folks are OOO or otherwise busy).

Could you DM me on CNCF Slack with the dates of your email & HackerOne disclosure?

**Comment by agilgur5** [comment]
The disclosure has been responded to, so I think this is being handled now

**Comment by agilgur5** [comment]
### misconfiguration with Secrets in plaintext

I ended up responding to the reporter (in great detail) and after checking with them as well as some SIG Security folks, I wanted to clarify here that this turned out to be a misconfiguration on their side. The misconfiguration has been fixed on their side.

Specifically, there were Secrets in plaintext manifests.
Their users used environment variables correctly, but defined them directly in the manifest -- instead they should use [k8s Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) and can refer to those Secrets by `name` (no secret contents) in the manifest by using [`valueFrom.secretKeyRef`](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data) within their `env` variable definition.
I referred to the [Secrets page](https://argo-workflows.readthedocs.io/en/latest/walk-through/secrets/) in the Argo docs that goes over the proper way of handling Secrets in Argo, which inherits from k8s and links to some of the k8s docs I referred to as well. As such this is also out-of-scope for Argo as it is a more generic k8s Secrets usage misconfiguration that is not specific to Argo.

As some of these kinds of misconfigurations can be fairly common with folks who are less experienced with k8s, IaC, and other Infra/DevOps best practices, I wanted to address that here for more user education on the topic for any other users who run into that (after having confirmed that was ok to do and the misconfigurations were resolved). 

### UI-only users

For UI-only users of Argo who don't have direct `kubectl` cluster access, either a cluster-admin / operator could create Secrets for them, or they could be given RBAC to `create` Secrets in the k8s Dashboard, as two common, generic options.

### Other Secrets tools

Other tools like the [External Secrets Operator](https://github.com/external-secrets/external-secrets), [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets), and more are useful for syncing external secret stores to k8s Secrets or encrypting Secrets in code, respectively.

### Existing Argo issues with regards to Secrets

There are some other issues in Argo related to Secrets, such as #8685, #5506, and #11431.
All of those are fairly complicated for the reason that Argo should not access, nor have access to, nor pass Secrets itself and should only rely on k8s Secrets that Pods use directly (without Argo as an intermediary). Argo is not a Secrets Manager and therefore should not itself manage Secrets (otherwise you get into a rabbit hole of secure Secrets Management and such, which is out-of-scope for Argo). Some of those issues are for feature parity with other CI tools, many of which do handle Secrets Management, whereas Argo leaves that to k8s's built-in (and ecosystem) mechanisms as it is k8s native.
