### ISSUE TITLE
Add `--no-color` support / ability to disable ANSI escape codes to `argo lint` command

### ISSUE THREAD

**Issue by menzenski** [argoproj/argo-workflows#12913]
# Summary

What change needs making?

I am trying to run `argo lint` with color disabled. I see that some CLI commands support a `--no-color` option, but `argo lint` does not.

* `argo get` supports `--no-color` https://argo-workflows.readthedocs.io/en/latest/cli/argo_logs/#options
* `argo logs` supports `--no-color` https://argo-workflows.readthedocs.io/en/latest/cli/argo_logs/#options

Other Argo CLI commands seem not to support this flag.

## Use Cases

When would you use this?

For me, the use case is running `argo lint --offline` in CI (GitHub Actions). I want to run the command, capture the output, and include it in a GitHub comment on a Pull Request. The ANSI escape codes make the output hard to read:

```
�[4mdev/my_workflow.yaml�[0m:
   �[31m✖�[0m in "my-workflow" (CronWorkflow): cannot validate Workflow: spec.arguments.file-name-suffix.value or spec.arguments.file-name-suffix.valueFrom is required

�[31m✖ 3 linting errors found!�[0m
```

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Does `argo lint -o simple` not suffice? The [simple formatter](https://github.com/argoproj/argo-workflows/blob/f0a867b6325ec3f20369bf6c92518dc5bb2ebf59/cmd/argo/lint/formatter_simple.go) should print without colors.

Otherwise, you'd need to add a `--no-color` flag to [`lint.go`](https://github.com/argoproj/argo-workflows/blob/f0a867b6325ec3f20369bf6c92518dc5bb2ebf59/cmd/argo/commands/lint.go) and pass that through to the [pretty formatter](https://github.com/argoproj/argo-workflows/blob/f0a867b6325ec3f20369bf6c92518dc5bb2ebf59/cmd/argo/lint/formatter_pretty.go), where you can use [`color.Toggle(false)`](https://github.com/TwiN/go-color/tree/v1.4.1?tab=readme-ov-file#disabling-colors) to disable colors

**Comment by menzenski** [comment]
> Does `argo lint -o simple` not suffice? The [simple formatter](https://github.com/argoproj/argo-workflows/blob/f0a867b6325ec3f20369bf6c92518dc5bb2ebf59/cmd/argo/lint/formatter_simple.go) should print without colors.

Yeah, sorry - I should have said in the original post that we are using `-o simple`. It works fine but the spacing of the "non-simple" output is easier to read when there are multiple issues.

Admittedly this is a small quality-of-life thing.

**Comment by agilgur5** [comment]
> Admittedly this is a small quality-of-life thing.

If you're interested in contributing, we have labeled it as a "good first issue" 😉

**Comment by miltalex** [comment]
@agilgur5 I could have a look if it is still up for grabs.
