### ISSUE TITLE
UI: Add option to use ISO 8601 (YYYY-MM-DD) timestamps

### ISSUE THREAD

**Issue by JPZ13** [argoproj/argo-workflows#12943]
# Summary
Provide the user or operator the option to display timestamps using the [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601)

## Use Cases
Whenever displaying dates in the UI, this will give users:
- An absolute time/day when workflows start/stop
- Less ambiguity for countries that use different time/day formats

Also, I think it matches how timestamps are done on the workflows CRDs

## Requirements
- Allow the user to specify in the `workflow-controller-configmap.yaml` whether they want ISO timestamps or the existing format

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by JPZ13** [comment]
Tagging @Adrien-D to work on it

**Comment by agilgur5** [comment]
> * Allow the user to specify in the `workflow-controller-configmap.yaml` whether they want ISO timestamps or the existing format

That would make it controller-wide as opposed to user preference. I might suggest following a user preference approach similar to the one that Isitha took for #10120. See also #12097. 

I have been considering adding a "Settings" page or section on existing page (e.g. UserInfo) for user preferences since we're getting increasing customization requests. Those could be for TZs like here, language like in #12682, and potentially sources for UI plugins (which could include localization sources).

> Whenever displaying dates in the UI

This might be non-trivial to find all these 😅 . We'd want to centralize some utility functions for this as well.

**Comment by JPZ13** [comment]
> That would make it controller-wide as opposed to user preference. I might suggest following a user preference approach similar to the one that Isitha took for https://github.com/argoproj/argo-workflows/pull/10120. See also https://github.com/argoproj/argo-workflows/pull/12097.

User preference makes sense. I'm happy with that

> This might be non-trivial to find all these 😅 . We'd want to centralize some utility functions for this as well.

Agreed. There isn't good standardization across the codebase. I think any PRs that move us forward for utility functions and standardizing things are good for the project. Additionally, it might be impossible to get all the timestamps on the first pass. Maybe the bar should just be getting the timestamps on the major views in the first PR and then having follow-on PRs to get the stragglers

**Comment by agilgur5** [comment]
> There isn't good standardization across the codebase.

Mm there are plenty of util functions, although yes there's many cases they're not always used in all places (e.g. #12970, #12973 etc etc) which is tech debt that causes bugs.

> on the major views in the first PR and then having follow-on PRs to get the stragglers

Sure. I think we can get more than just the major views though on a first pass
