### ISSUE TITLE
`make docs` reorders `.spelling` as case-insensitive on Mac

### ISSUE THREAD

**Issue by Adrien-D** [argoproj/argo-workflows#13142]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When I run `make docs` on my mac, it reorders the `.spelling` list by `case-insensitive` and not `case-sensitive` as specified in #12521

Could we add something like `sort -f` to uniformise the behavior of `sort` ?

### Version

v3.5.7

**Comment by agilgur5** [comment]
> Could we add something like `sort -f` to uniformise the behavior of `sort` ?

It's the other way around -- `sort` is default case-sensitive, and `--ignore-case` / `-f` makes it case-_in_sensitive.

This sounds like potentially a [Mac issue](https://superuser.com/q/1355507/584649) with non-GNU `sort`. Although I tested on my own Mac per the PR "Verification" and had correct results 🤔 

```
❯ sort --version
2.3-Apple (165.100.8)
```

is what I have, although I did update this week to Sonoma (macOS 14), so that's not what I used while testing

**Comment by agilgur5** [comment]
@Adrien-D can you check if #13370 fixes this for you?

**Comment by Adrien-D** [comment]
@agilgur5 exactly #13370 fixed it me for me, closing this issue
