### ISSUE TITLE
Add taskname to the workflow pod's name

### ISSUE THREAD

**Issue by ian-howell** [argoproj/argo-workflows#1319]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:
Currently, running a workflow creates a pod for each task, and each of those pods gets a unique name associated with the workflow. So if I run a workflow which has 3 steps, then I run `kubectl get pods`, I get something like this:

```
NAME                                  READY     STATUS              RESTARTS   AGE
wf-install-1938236639                 0/1       Completed           0          16s
wf-install-3464818                    0/2       Completed           0          23s
wf-install-3672310916                 0/2       Completed           0          23s
wf-install-376633117                  0/2       Completed           0          23s
```

**What you expected to happen**:
This is pretty annoying, because it makes it very hard to determine which pod is doing which task. I propose adding the task name to the pod name, such that the previous step looks something like the following:
```
NAME                                  READY     STATUS              RESTARTS   AGE
wf-install-1938236639                 0/1       Completed           0          16s
wf-install-db-init-3464818            0/2       Completed           0          23s
wf-install-setup-host-3672310916      0/2       Completed           0          23s
wf-install-send-email-376633117       0/2       Completed           0          23s
```

**Comment by alexec** [comment]
I don't think we can change this because it would break existing installs. 

What about annotating pods with the step name or similar.

**Comment by xinbinhuang** [comment]
Maybe relevant to this, I wonder how does `argo get` recognize the name of each step?

**Comment by astanway** [comment]
Pod annotation would certainly be an improvement if we can't do pod names.

**Comment by afoltzm** [comment]
@alexc I can understand not wanting to break existing installs by changing the default behavior - is there a way it can be a configurable option in the workflow controller configmap that defaults to the existing method? That way it can be 'opt-in' for administrators who want that level of control and understand the risks. In addition to improving logging systems, this change would also make it easier for external systems that make use of Argo artifacts to identify those artifacts by step.

**Comment by alexec** [comment]
@afoltzm changing pod names means that workflows break during upgrades. So this changes is highly risky, and not popular enough to warrant configuration option. The name of workflow can be found from the `workflows.argoproj.io/workflow` label.

**Comment by alexec** [comment]
We'd need to find a way to make this forwards/backwards compatible. I.e. add the task name to the pod, but recognise legacy names too.

**Comment by boundless-thread** [comment]
@alexec What are the complications to this that you know of?  Can you explain a bit more about "changing pod names means that workflows break during upgrades"? I've done a cursory look at the workflow controller code to see if this is possible.  From my understanding a pod is named from a `nodeId` which is determined from a `nodeName`.

https://github.com/argoproj/argo/blob/master/workflow/controller/workflowpod.go#L131

An example log output for a stepped workflow is 
```
[workflow-controller-6d9959f4b7-kgqp5] time="2020-10-21T17:39:45Z" level=info msg="Created pod: steps-c92g4[0].hello1 (steps-c92g4-146450447)" namespace=workflows workflow=steps-c92g4 
```
Where `nodeName` is `steps-c92g4[0].hello1` and `nodeId` (or pod name) is `steps-c92g4-146450447`.  

An example log output for a DAG workflows is:
```
[workflow-controller-6d9959f4b7-kgqp5] time="2020-10-21T17:36:18Z" level=info msg="Created pod: dag-diamond-f5btw.B (dag-diamond-f5btw-2817751619)" namespace=workflows workflow=dag-diamond-f5btw 
```

Also, pods are already annotated with node-name.

Thinking out loud and with my limited knowledge of the code base, it seems the `podInformer` is storing the pods in a cache indexed by their name.  If thats true, it might be possible to change the indexer to cache by the `nodeId` created from the pod annotation value of `node-name`.  I think this would provide backwards compatibility since the pods are already annotated with node-name and the end result is the `nodeId`.   This could allow us to specify an arbitrary pattern for the pod names (e.g. `prefix-<workflow>-<type>-<step level>-<task name>-HASH`)

**Comment by christopheblin** [comment]
As a (limited) workaround, you can do :

    k get pods -o custom-columns=NAME:".metadata.annotations.workflows.argoproj.io/node-name",STATUS:.status.phase,POD:.metadata.name
    
this will give you the name of the step in the name

If you want to see only for one exec : 

    k get pods -o custom-columns=NAME:".metadata.annotations.workflows.argoproj.io/node-name",STATUS:.status.phase,POD:.metadata.name -l workflows.argoproj.io/workflow=dataset-5wkj2
    NAME                        STATUS      POD
    dataset-5wkj2[0].download   Succeeded   dataset-5wkj2-3987170723
    dataset-5wkj2[1].unzip      Succeeded   dataset-5wkj2-983027098

**Comment by alexec** [comment]
I've created a PoC for this issue (see above link).

I'm looking for someone from the community to take it across the finish line. Please ping me if you'd be interested in that.
