### ISSUE TITLE
v3.5.9 UI: Clicking pod logs button crashes UI

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#13415]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

- Install 3.5.9
- Run a workflow
- Click a node on the running workflow
- Click 'logs' in the 'summary' tab
crash:

![image](https://github.com/user-attachments/assets/0b3a2249-35c7-4796-bb55-93762e4e319c)

There are no relevant server logs.

Workaround:
Roll back to 3.5.8

Edit:  I would encourage others to use the thumb emoji rather than an unnecessary "we have this issue too"-style comment.

### Version(s)

v3.5.9

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any workflow.
```

### Logs from the workflow controller

```text
Nothing useful
```

### Logs from in your workflow's wait container

```text
not relevant
```

**Comment by ab-sk-no** [comment]
Verified, we have that, too.

**Comment by tchatzig** [comment]
Just upgraded from `v3.5.8` to `v3.5.9` and we have the same issue.

**Comment by agilgur5** [comment]
Huh, I'm pretty surprised this didn't get caught by static analysis by the type-checker during build or the linter. The `release-3.5` branch never brought in linter migrations (#12163), but this would still be surprising that an older linter wouldn't detect it 🤔 My type-checker in my editor detects this instantly. 

This appears to be due to out-of-order cherry-picking; #12973 was cherry-picked before #12964. In fact, it was cherry-picked into an older patch (v3.5.7) because it was a fix, while #12973 is a refactor that was cherry-picked only for 3.5.9 in order to resolve merge conflicts for #13039 etc.

**Comment by agilgur5** [comment]
> I'm still not sure how the [build's `ts-loader`](https://github.com/argoproj/argo-workflows/blob/77dcfdc80369bc977a625f0899ad3ef6650ae182/ui/src/app/webpack.config.js#L38) doesn't catch this on type-check though. That's odd 🤔

I suspected that the `transpileOnly` flag doesn't actually accept `false` and is just "supplied or not". Removing the flag indeed causes type errors to pop up: this one, but also a few other internal ones (that are purely type-related and do not affect the resulting JS), and the `node_modules` ones due to https://github.com/ramda/types/issues/64. As a result, I can't quite enable that in the `release-3.5` branch to prevent this in the future. I think it might be worthwhile in this case to backport UI build/toolchain changes from `main`, but will confer with other contributors as it outside our normal process.

In the interim, I'll push up a small fix for this and should have 3.5.10 out tonight as this is affecting lots of people (I guess that it's good that the UI is popular at least!)

**Comment by agilgur5** [comment]
This has been fixed in 72d0d22e6254c2871f7f4f3798a362094409064f and included in [v3.5.10](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.10)

(commit ref is bc it only exists on the `release-3.5` branch since this bug does not exist on `main` as it was due to out of order cherry-picking per above)

**Comment by tchatzig** [comment]
Thanks @agilgur5 
that was a quick fix 💯

**Comment by ab-sk-no** [comment]
Indded. Thank you!
