### ISSUE TITLE
UI (when 2 tabs open) 3.6.0rc4 - submit workflowtemplate greyed out

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13892]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

in the ui it lets me create a new workflowtemplate and update it, but the button to submit it is greyed out. i'm using the quickstart

### Version(s)

3.6.0rc4

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
default
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

n/a
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

n/a
```

**Comment by Joibel** [comment]
I can reproduce this on firefox 131 on linux. I don't need a hard refresh, just a normal refresh to make the button appear, and the button appears greyed out without 2 tabs.

**Comment by MasonM** [comment]
@tooptoop4 The "submit" button was completely broken before that change for the reasons described at https://github.com/argoproj/argo-workflows/pull/13593, so it definitely didn't cause this. If this was a regression, it dates back at least to https://github.com/argoproj/argo-workflows/pull/13069

**Comment by MasonM** [comment]
Looking at this more, I think this is a consequence of reference equality checking. In my original fix for https://github.com/argoproj/argo-workflows/pull/13593, I had it use deep equality comparisons, which doesn't have this problem. However, I  reverted that in https://github.com/argoproj/argo-workflows/pull/13593/commits/24c0206b9071503467034cb67716ef0b27158b0f because Anton had concerns about performance (see https://github.com/argoproj/argo-workflows/pull/13593#discussion_r1769673834). I did figure out a way to fix this without affecting performance (see https://github.com/argoproj/argo-workflows/pull/13593#discussion_r1781972661), but the problem is that's a significant change, and I don't know if there's anyone left that can code review such a change. So I think we're just going to have to live with this until there's someone available to code review UI changes.

**Comment by MasonM** [comment]
@isubasinghe Thanks! I cleaned up the POC and entered https://github.com/argoproj/argo-workflows/pull/13915 for this

**Comment by MasonM** [comment]
Re-opening because there's another issue that causes this: clicking the "Update" button after editing an object. https://github.com/argoproj/argo-workflows/pull/13915 will fix that.
