### ISSUE TITLE
Auto-delete workflows on archive

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo-workflows#2001]
# Summary

During the community meeting, I believe something was mentioned like "once a workflow is archived, you can go in and delete it". I think it'd be nice to have a config toggle that makes the behavior automatic.

# Motivation

My workflows generate ~large persistent volumes, with ownership set so the volumes get deleted when the workflow is deleted. It'd be ideal if I could configure the Argo server to:
1. Auto-archive workflows as they succeed (#2000)
2. Auto-delete archived workflows

That way volumes get cleaned up automatically in the happy path, but they're kept around for retries when things fail.

# Proposal

I'm not sure about the internals, but at the config level I'd expect to see something like this:
```yaml
persistence:
  archive:
    # Default: false
    autoDelete: true
```

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
cc @alexec

**Comment by alexec** [comment]
@jessesuen can this be done using TTL?

**Comment by jessesuen** [comment]
Yes, this can be done using the `spec.ttlStrategy` feature in v2.5, or `spec.ttlTimeAfterFinished` prior to v2.5. 

That said, I think there might be a feature in here where the controller could be configured with a "default" ttlStrategy so that all workflows fall back to (if not specified in the spec). In this case, workflows which wish to *not* auto-delete is could be specified as:

```yaml
spec:
  ttlStrategy: {}
```

**Comment by tooptoop4** [comment]
can this be closed? already implemented i believe

**Comment by qa-denis-huber** [comment]
Hi there! I have a quick question regarding this issue being marked as "completed."

The original request was for a feature to **automatically delete Kubernetes workflow resources *immediately after* they have been successfully archived to the database** (e.g., a flag like `persistence.archive.autoDelete: true`).

Although the issue was closed in September 2024 as "already implemented," I am unable to find this specific functionality in the current codebase.

**My Analysis of Current Features:**
I reviewed the existing options, but they seem to address different needs:
* `archiveTTL`: Deletes records from the **Database** (not the K8s resource).
* `ttlStrategy`: Deletes from K8s based on **Time** (not archive completion status).
* `retentionPolicy`: Deletes from K8s based on **Count** (not archive completion status).
*  The archiving process only saves workflows to the database - it does not delete the K8s resources.

**The Gap:**
Currently, using `ttlStrategy` alongside archiving is a time-based workaround, not an event-based guarantee. It does not ensure that the resource is deleted *only if* the archive was successful.

**Clarification Request:**
Is there actually a configuration option to automatically delete the Kubernetes workflow resource strictly upon successful archiving? If so, could you please point me to:
1.  The specific configuration parameter name.
2.  Relevant documentation or an example.
3.  The code implementation handling this logic.

If this specific "delete-on-archive-success" mechanism does not exist, could we please **reopen this issue**?

Thanks for the guidance!
