### ISSUE TITLE
Argo stress test

### ISSUE THREAD

**Issue by merlintang** [argoproj/argo-workflows#2899]
# Summary

Currently, for each release, we do not provide the stress test. The stress test would help us to understand the system performance like throughput and scalability for each release. 

# Motivation

As introduced above

# Proposal
We can test Argo runtime performance w.r.t the number of pods, jobs and concurrent workflows. 

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by rosscdh** [comment]
CPU stress, memory stress, network stress and random fail with backlog would be interesting.

Max archived
Max num  cronworkflows
Max nun templated workflows
Max num cronworkflow start spike

**Comment by alexec** [comment]
See #3751

**Comment by alexec** [comment]
This dovetails with the FMEA testing I've been doing recently.

Essentially I run a workflow that create other workflows. This workflow in parameterized as follows:

- X - how many workflows to create
- Y - how many pods each workflow then create

Initially scheduling the workflow you'll see "Deadline exceeded" - there is a bug in the DAG code (#3905) that needs fixing to address this.

Then you'll see the following errors

- `Operation cannot be fulfilled...Conflict`  - I'm not sure what is causing this
- `pod ... deleted` - this is caused by Kubernetes eviction

What I'm doing next in running various scenarios, e.g. 1000x1 (1000 concurrent workflows with 1 pod).

**Comment by alexec** [comment]
See #3918
