### ISSUE TITLE
WorkflowTemplate version

### ISSUE THREAD

**Issue by aviklai** [argoproj/argo-workflows#3013]
# Summary
Is it possible to add support for custom metadata containing the version for the WorkflowTemplate? the version can be filled by the creator of the WorkflowTemplate.
# Motivation
Allow WorkflowTemplate maintainers to know which version of the WorkflowTemplate exists in the server.
I would like to automatically compile and deploy WorkflowTemplates using kfp and with each deployment change the version of the WorkflowTemplate.
# Proposal
To add support for custom metadata property to allow adding the version of the WorkflowTemplate.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@dtaniwaki ?

**Comment by dtaniwaki** [comment]
We currently store resolved templates per `Template` instead of per `WorkflowTemplate` in the `Workflow` status, so if we want to store something at the `WorkflowTemplate` level, there's no place for them. I don't come up with a good place for them now, but I think this kind of feature is useful.

By the way, you can add a parameter of the version which is stored into stored templates to achieve it for now.

**Comment by alexec** [comment]
Kubernetes already have a way to store meta-data that TektonCD Catalog leverages. 

They put it in `app.kubernetes.io/version`

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

That said, there is nothing to stop you adding almost  any annotation or label you like to a workflow.

**Comment by aviklai** [comment]
Thanks - it works.
