### ISSUE TITLE
Correct timezone in logs

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3474]
The logs provided by the UI are timestamped. The dates and times provided are always the European ones.

I tried to set `TZ=America/Toronto` to both the `workflow-controller` and `argo-server` deployment without success.

Is that possible to configure the timezone?

**Comment by alexec** [comment]
The timestamps in the logs are standard GMT (was UTC) timestamps. It is not currently configurable, but I think it would be easy to contribute a change to enable this. Would you be intested?

**Comment by hadim** [comment]
I am new to golang but happy to help if you point me in the right direction.

**Comment by hadim** [comment]
I guess it's simple to do that on the UI side. But would be better to have this option on the server-side right?

**Comment by alexec** [comment]
I would implement this on the UI side, as it is a display issue. 

Looking at the code:

https://github.com/argoproj/argo/blob/master/ui/src/app/workflows/components/workflow-logs-viewer/full-height-logs-viewer.tsx#L18

That is where to make the fix.

**Comment by DhwanishShah** [comment]
Hi I want to contrubute in this. Can you assign me for this issue? @caelan-io @alexec @hadim

**Comment by caelan-io** [comment]
Great to hear. Please feel free to get started and open a pr once ready for review. I can support you on this @DhwanishShah

**Comment by yay14** [comment]
@sarabala1979 @caelan-io is this issue solved? can i see logs in my local timezone now? can you also point to what changes are required?

**Comment by caelan-io** [comment]
@yay14 - please see this comment on the PR: https://github.com/argoproj/argo-workflows/pull/10120#issuecomment-1332915742

**Comment by yay14** [comment]
@caelan-io since the default timezone of argo controller and server is UTC, we are pushing logs via a script which is running on argo, so there the timezone picked from env is UTC and I want to change that to local, is there a way to do that?

We are using the following logger config
`
logging.basicConfig(
    stream=sys.stderr,
    level=logging.INFO,
    format="%(asctime)s: %(levelname)s: %(name)s: %(message)s",
    datefmt="%m/%d/%Y %I:%M:%S %p"
)
<img width="1525" alt="Screenshot 2023-03-15 at 2 24 38 PM" src="https://user-images.githubusercontent.com/41835298/225257328-4e0128d7-425a-41b2-b7a1-9fdc119d249c.png">
`
