### ISSUE TITLE
Be able to list more workflows on GUI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3590]
# Summary

Make listing many workflows fast.

# Motivation

It is too slow, this may well be a bug.

# Proposal

* Are we correctly filtering the response?
* Are we only getting updates?
* Are we using resourceVersion to filter?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
After more investigating and talking to users, seems like this issue is limited to <2.9. A user who experienced the issue (@salanki) said that a slow was experienced around 100 workflows, all of them in versions <2.9. During testing I was able to list up to 500 workflows without any noticeable slowdowns.

The most likely fix for this issue was https://github.com/argoproj/argo/pull/3165 and https://github.com/argoproj/argo/pull/3228

Please comment if slowdowns are still experienced in 2.9+

**Comment by simster7** [comment]
Consider new StreamForwarder code in Argo pkg for this: https://github.com/argoproj/pkg/blob/master/grpc/http/forwarders.go#L136

**Comment by alexec** [comment]
Closing as `wontfix` and we have reports that v2.9 solves this issue.
