### ISSUE TITLE
Recommend approach to "apply" CronWorkflow

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#3951]
# Summary

We'd like to deploy our `CronWorkflow`s as part of a CD process. What's the recommended approach to "apply" a `CronWorkflow`, where they may or may not exist? A couple of draft options:

#### Delete & create
e.g. `argo template delete --all; argo template create workflows/*.yaml` 
This is fine, but if there's an error in one of them, it'll leave it deleted rather than unchanged. 
There's also some corner case that the workflow trigger falls between the delete and create.

#### kubectl
e.g. `kubectl apply -f workflows/*.yaml` 
I think this fulfills the goal, but it returns a non-zero exit code of `error: from {}-workflow-: cannot use generate name with apply` if there are non-cron or template objects. 
I'd have thought given Argo's focus on declarative approaches, this would be a 'golden path', so I hesitated to use a non-argo command. Or is this the recommended approach/

Thanks again for the superb tool!

**Comment by simster7** [comment]
First, to apply CronWorkflows you should use `argo cron create`, not `argo template create`. (same with `delete`)

How about using [Argo CD](https://github.com/argoproj/argo-cd) for this? Argo CD will automatically apply your CronWorkflow objects to the cluster based on changes on a Git repo.

Otherwise, maybe an `argo replace` command will be needed. I'll discuss with the team.

**Comment by max-sixty** [comment]
Thanks @simster7 !

Do you know off-hand what command Argo CD uses? I'm certainly open to using it; to the extent it's calling a standard command, that would make allow some of the functionality without committing to the whole product.

**Comment by simster7** [comment]
> Do you know off-hand what command Argo CD uses?

Not sure off hand, sorry. Feel free to ask there :)
