### ISSUE TITLE
Long time for Github Actions to build images

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4062]
# Summary

This used to take 20m. Now takes 2h.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@lippertmarkus @dgiebert any thoughts on making this faster. Primarily the multi-platform images could be faster.

**Comment by lippertmarkus** [comment]
When looking at the history, https://github.com/argoproj/argo/pull/3848 introduces changes which took the time from 8 minutes to 1,5-2h

**Comment by alexec** [comment]
New master build needs monitoring:

https://github.com/argoproj/argo/actions/runs/269018753

**Comment by lippertmarkus** [comment]
@alexec I now tried 2 things:
1. Using Travis CI for building and pushing images. It has support for ARM64 and the complete build and push for all images takes around 13mins: 
    ![image](https://user-images.githubusercontent.com/1463140/94120096-04d30b00-fe50-11ea-8d96-24f09897039b.png)

    Travis CI is subscription-based, but should be backed by CNCF: https://www.cncf.io/services-for-projects/#continuous-integration

1. Like described in https://github.com/argoproj/argo/pull/4111#issuecomment-697642045 first making the images for amd64 available and when the others finished updating the manifest.
    linux/amd64 are available after 8mins:
    ![image](https://user-images.githubusercontent.com/1463140/94123215-cb9c9a00-fe53-11ea-9fae-fb44d4329c24.png)
    Manifest is updated with linux/arm64 and windows images after 45mins:
    ![image](https://user-images.githubusercontent.com/1463140/94128953-0f46d200-fe5b-11ea-9bc6-3a9fa81c39de.png)



When using Travis CI is backed by CNCF I would prefer this way because then all images would be immediately available when we release a new version and not just the linux/amd64 ones with the windows and linux/arm64 ones follow half an hour later.

What do you think?

**Comment by alexec** [comment]
We moved off CircleCI to Github Actions to keep it cheap and simpler. Lets run with what we have, and see if that's good enough.

Thank you for taking the extra look in.

**Comment by lippertmarkus** [comment]
Ok, done in https://github.com/argoproj/argo/pull/4127

We could also think about automating the creation of the release. Then you wouldn't need to wait and it would be irrelevant how long building images takes.
