### ISSUE TITLE
Better support for govaluate expressions 

### ISSUE THREAD

**Issue by christophschnabl** [argoproj/argo-workflows#4153]
# Summary
I found out that Argo is using `govaluate` to parse `when` conditional expressions. I played around with it and turns out most of govaluate works out of the box. However, the regex comparison operator seems to be very flaky with all the yaml parsing (json mapping) etc stuff. I compiled a list of some expressions and their respective outcome, below 
| expression in yaml  | output  |
|---|---|
| `when: "a11 =~ a1\\d"`              | `when 'a11 =~ a1\d` |
| `when: "a11 =~ a1\\d+" `           | `Invalid 'when' expression 'a11 =~ a1\d+': Unexpected end of expression` |
|  `when: "a11 =~ a1\\\\d"`           | `works` |
| `"a112 =~ a\\\\d{3}" `                 |  'Invalid 'when' expression 'a112 =~ a\\d{3}': Invalid token: '{' (hint: try wrapping the affected expression in quotes ("))'` |
|  `when: "'a112 =~ a\\\\d{3}'" `    |  `Expected boolean evaluation for ''a112 =~ a\\d{3}''. Got a112 =~ a\d{3}` |
|  `when: "\"a112 =~ a\\\\d{3}\""`  | `expected boolean evaluation for '"a112 =~ a\\d{3}"'. Got a112 =~ a\d{3}` |

# Use Cases

When would you use this?

I would use that quite often to evaluate expression in a regex like style. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
We use https://github.com/antonmedv/expr for evaluation in `depends:` logic and have been considering switching the `when:` logic to it as well. However, since the issue here seems to be related to the yaml itself, I'm not sure if making the switch would fix this particular issue. Maybe you can test that for us?

Meanwhile, as a workaround I can suggest you add a new container step right before the relevant `when:` step and perform the regex in said container. The container can then output `true` or `false` and then you can use its result on the field like so `when: {{steps.regex.outputs.result}}`. Does this make sense?

**Comment by christophschnabl** [comment]
Yeah, will test it and add my findings in this ticket.

Ad) workaround - yes this would be another option. However being able to use regexp would make the `when` statement ever so elegant and powerful.

**Comment by catfalls** [comment]
I found that if you wrap the left and right expressions with single quotes respectively, the error will go away. For example, for
```
when: "a11 =~ a1\\d+"
```

the working version would be
```
when: "'a11' =~ 'a1\\d+'"
```

**Comment by scravy** [comment]
I came here as I was confused as to whether `govaluate` or `expr` is used in `when:`

To me it is very confusing to find `when:` use one library, but `depends:` and `{{#` use another one.

**Comment by alexec** [comment]
We're moving away from `govaluate`. Closing issue.

**Comment by agilgur5** [comment]
See #7831 and related issues for moving away from `govaluate`
