### ISSUE TITLE
Need ability to change parameters/arguments while submitting/re-submitting workflows in Argo UI

### ISSUE THREAD

**Issue by amoldharamshi** [argoproj/argo-workflows#4662]
# Summary

Need ability to change parameters/arguments while resubmitting workflows in Argo UI

# Use Case

In case of failures or if we want to run the workflow again with different parameters/arguments, we need ability to do so using Argo UI

**Comment by alexec** [comment]
Thank you @amoldharamshi I'll speak to my colleagues about your request.

**Comment by alexec** [comment]
Might be good to fix #3453 at the same time. I'm imagining a new panel that pops up similar to submitting from workflow templates. That would be neat.

**Comment by simster7** [comment]
I added the ability to set parameters in the workflow submit pane. It's a little trickier to add this in the workflow resubmit pane. I will bring this up with the team tomorrow

**Comment by simster7** [comment]
Done

**Comment by alexec** [comment]
Re-opening so we can do this.

**Comment by Guillermogsjc** [comment]
Hi, 

it would be really useful to allow to the client function `resubmit` to to this. 

Something like

`argo resubmit -n argo -p UPDATED_PARAMETER=updated_value EXECUTED_WORKFLOW`

The use case is pretty clear, you want to retry a workflow changing some parameters.

**Comment by alexec** [comment]
This issue is about UI. Please raise new issue.

**Comment by kennytrytek-wf** [comment]
I'd like to take this one, please. My understanding is that the resubmit UI should have an option in addition to the `OK` and `Cancel` buttons to update parameter values before submission. I'm not sure of the best solution for all cases.

For workflow templates and cluster workflow templates, I think it would be good to redirect to the template submission view with the inputs pre-filled on the selected entrypoint, since that would help give a consistent experience submitting workflow templates from the UI.

The difficulty comes for non-template workflows. It seems like we would need a new submit panel that did essentially the same thing as the template submission, but for a workflow that doesn't have a defined template. I don't want to duplicate all the same submit logic in a new place; would it be possible to use the same workflow submission form for both workflow templates and free-form workflows?

**Comment by kennytrytek-wf** [comment]
Looking through the code a bit more, this actually seems like it's largely already solved in this case:
https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/workflows/components/workflow-creator.tsx

I'd like to propose the following behavior when clicking the Resubmit button:
* For a [cluster] workflow template, the `SubmitWorkflowPanel` side panel is shown, populated with the entrypoint and parameter values that were used in the workflow. Submission will issue a `submit` request.
* For a non-templated workflow, the `WorkflowEditor` panel is shown, populated with any information available in the executed workflow. Submission will issue a `create` request.

**Comment by terrytangyuan** [comment]
@toyamagu-2021 Can you comment here so that I can assign this to you?

**Comment by toyamagu-2021** [comment]
@terrytangyuan 
Thank you for your mention!
