### ISSUE TITLE
Improve the docs!

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5329]
But what specifically needs improving? Please comment!

**Comment by wdma** [comment]
I think it would be useful to have a bit more documentation on the Quickstart page.  In particular, what is the expected starting point?  Here is the Quickstart page for Calico as an example of what I think would be nice: https://docs.projectcalico.org/getting-started/kubernetes/quickstart 

I have been developing successfully the Argo Quickstart manifest, but as I have grown, I now want to use the standard installation and am running into problems as describe here (https://github.com/argoproj/argo-workflows/issues/5380).  I have gone as far as I can with debugging. I now think the issue may be because I am lacking some necessary prerequisites, but I do not know where to look!  

I would be happy to help with documentation!

**Comment by terrytangyuan** [comment]
One thing I saw people asking a lot is technical details of the implementation that would help them maintain their Argo Workflows deployments. For example, https://argoproj.github.io/argo-workflows/environment-variables/ is a good start but we could do a better job highlighting various configuration options for people to manage different scalability/stability issues on their clusters (although these are experimental features they are being looked up rather frequently). Another example is that we are lacking technical documentation around Argo CLI commands, e.g. how do `retry` and `resubmit` work internally (without looking up in the code) and what the prerequisites are in order to use them (e.g. the completed workflows being retried/resubmitted need to exist).

**Comment by kevin-hanselman** [comment]
I'll preface this by saying that I generally like Argo Workflows. This post is an honest attempt at constructive criticism. Thank you all for your work!
  
Poor documentation is one of the largest obstacles for me to broadly recommend Argo Workflows. The documentation is minimally helpful and often confuses more than it helps. In particular, the "Beginner/Intermediate/Advanced" distinction in the User Guide is not conducive to answering questions and/or solving problems. The documentation should be rethought and reworked to [optimize for answering user's questions in different, orthogonal ways](https://documentation.divio.com/).

Take, for example, the user experience of wanting to learn about Artifacts and Artifact Repositories. I might try the search bar first. Unfortunately, this only returns API reference documentation. So then I might look in Core Concepts, but that gives me hardly any actionable information. Then I might wander aimlessly around the Beginner/Intermediate/Advanced sections of the User Guide. The first thing I find is probably "Intermediate/Artifact Repository Ref", which doesn't answer the question of how Artifacts work or how to use them in workflows. If I'm a curious newcomer, I may abandon the site in dismay.

I would recommend adopting [this taxonomy](https://documentation.divio.com/) for documentation, which has clear audiences and lines of questioning in mind for different styles of documentation.
