### ISSUE TITLE
Do you want Python 1st-class support?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5330]
And what does that even mean? Did you read [this blog post](https://blog.argoproj.io/authoring-and-submitting-argo-workflows-using-python-aff9a070d95f)?

**Comment by ecurtin2** [comment]
First, I'd like to thank all the contributors for a lovely project. I'll try and help the discussion here with my perspective. 

I've been using argo workflows for about 2 years now in the context of ML pipelines and have been quite happy. The problems that I personally come across that I think would be aided by top tier python support are:

1. Code reuse via normal language constructs (and python package repository, PyPI)
2. Quality control of using linters, formatters etc (don't let indentation errors propagate to runtime)
3. Quick onboarding by removal of boilerplate

The above points can be accomplished in any language of course, but the reason python is attractive for this is

4. Simplicity 
5. **Already known by data scientists and analytical users**

As we're scaling to more users internally, point 5 is IMO the most important reason for choosing python over other languages. 

As for implementation I'm aware of 3 options:

 - Kubeflow pipeline DSL: https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html
 - Couler: https://github.com/couler-proj/couler
 - Argo dsl: https://github.com/argoproj-labs/argo-python-dsl

Kubeflow DSL might actually accomplish what I need, but last time I tried this I got an argo version conflict (dsl incompatible with my argo version? I admit I didn't give this a ton of debugging effort.), although that might not be an issue any longer. 

I think a decent python client is definitely sufficient. A problem I've encountered in things like openAPI generated clients is difficulty for users figuring out valid parameters, since I think the most common client generators (proto and openapi) are a lot of dynamic attributes rather than say, dataclasses for the data structures.

**Comment by sylock** [comment]
I would be really happy of this feature also. 
I use almost only python scripts and I was also thinking about a way to ease the coding, since from a IDE (like Visual Studio Code) where your python code is just a string of a yaml field, you don't get all the help like syntax highlighting etc.

One "hack" would be to store locally workflow definition using kustomize. And with json patches, adding .py files in the content of the "script" field. It would just need a `kustomize build` before applying to the argo server.
I didn't know the argo dsl option. I'll check.

**Comment by terrytangyuan** [comment]
There is now an interactive Katacoda course that teaches step-by-step on how to write and submit your first Argo workflow using [Couler Python SDK](https://github.com/couler-proj/couler). Thanks @alexec for setting it up!

You can play with it right from your browser so please check it out and let us know what you think! https://github.com/couler-proj/couler#try-couler-with-argo-workflows
