### ISSUE TITLE
UI: Add autocomplete for labels in Archived Workflows

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5495]
## Summary 

1. Go to `/workflows` and click on the 'labels' filter. You see a dropdown which narrows the results as you type.
2. Go to `/archived-workflows` and click on the 'labels' filter. There is no dropdown.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0 rc8

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tim-sendible** [comment]
This is the same on the /reports tab too

**Comment by simster7** [comment]
It doesn't seem we even return a workflow's labels when querying the archive:

https://github.com/argoproj/argo-workflows/blob/dfe6ceb430d2bd7c13987624105450a0994e08fc/persist/sqldb/workflow_archive.go#L160-L165

In fact, labels are added to a separate table than the workflow itself:

https://github.com/argoproj/argo-workflows/blob/dfe6ceb430d2bd7c13987624105450a0994e08fc/persist/sqldb/workflow_archive.go#L114-L120

@alexec Is there a reason for this? Should we expect to not return labels when querying archived workflows? Or should we do so in a separate call?

If we should not be returning labels, then we should remove the label selector from the UI. If we should be, then we should edit the interface code to actually include the labels with the requested workflows.

**Comment by alexec** [comment]
Labels are not returned by the list operation, so they cannot be filtered client side. A label selector can be sent as a query parameter.

This is intentional - the archive can easily contain >= 10k workflows and we don't want to make the query complex.

This means that auto-complete cannot work client-side. We should keep the ability to query based on labels, but we cannot support auto-complete. I don't think auto-complete can even work for the normal workflow list as there is no way to know all the possible labels.

**Comment by simster7** [comment]
> This means that auto-complete cannot work client-side. We should keep the ability to query based on labels, but we cannot support auto-complete. I don't think auto-complete can even work for the normal workflow list as there is no way to know all the possible labels.

:+1: 

No change needed, then. Close?

**Comment by tim-sendible** [comment]
Ah. That immediately makes archives useless to us. Shame ☹️

**Comment by dcherman** [comment]
I wouldn't mind taking a stab at this at some point, it's been something that's irked me as well when I've wanted to search the workflow archive.

I don't think the query would be significantly complex, though we would need to discuss limits on the overall amount of data returned since as you pointed out, the archive could contain a large number of workflows.  We could also discuss ways to tweak the UI to support simplified queries.

For example, we could do

```sql
select name, value from argo_archived_workfow_labels where name like 'foo%' and value like 'bar% limit 100'
```

to support a very basic typeahead where `foo` and `bar` come from the client as search params.  Depending on the overall size of the table, that might be sufficient.  If we needed to scale higher, we could probably break this query up a bit.  Since the number of distinct label names relative to the number of distinct label values is likely much lower, we could first filter on label names and use `=` rather than `like` which should make querying much more efficient since the DB should only need to perform `like` on a subset of the overall table, though we'd have to check the query plan to make sure that assertion is correct.

**Comment by alexec** [comment]
@tim-sendible that can't be correct surely? You CAN query on labels, we just don't support auto-complete in the UI.

@dcherman I think you're idea sounds good. We could have a new endpoint (e.g. WorkflowArchive.ListLabels) that lists the labels and their values by querying `argo_archived_workflows_labels`. 

Looking at the schema, that table needs (I think it should have always had) an index on (name,value,clustername,uid) so you'll need to add that.

**Comment by tim-sendible** [comment]
@alexec without auto complete (internal) end users won't know the syntax to use. I'm trying to lower the barrier to entry.

**Comment by dcherman** [comment]
Mind assigning this one over to me?  I'm currently working on it as time allows when I can steal 30m here or there, hoping to have an MVP to share/review within a couple weeks.

**Comment by tczhao** [comment]
Hi @dcherman, 
I want to give this a go, 
I'm wondering if you are still working on this?

**Comment by dcherman** [comment]
@tczhao Other stuff has taken priority at the moment and I'm not actively working on this, so feel free to take a stab at this if you'd like

**Comment by tczhao** [comment]
Thank you @dcherman,
I will take a look
