### ISSUE TITLE
Unified logs viewer

### ISSUE THREAD

**Issue by jacek-jablonski** [argoproj/argo-workflows#5504]
# Summary

In the Workflow status window, it is possible to display logs emitted by the container. At this moment, the logs viewer displays the logs directly from the container until the workflow is archived. This means that if the workflow is completed and the pod is deleted, the log viewer will be empty, even though the logs have been emitted by the container. In this case, logs should be found under the link leading to the artifacts.
The above situation is surprising for people who are not familiar with the internal mechanisms of the Argo Workflows. Logs in the viewer should always be visible and easily accessible, regardless of the state of the container or their source, because they are often one of the most important elements with which the user interacts when using the UI.

# Use Cases

Through most of the times when I use the UI.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tim-sendible** [comment]
This may or may not help, we use Loki to aggregate all our k8s logs into one place, so using the 'links' option, we place a direct link at pod and workflow level to the loki logs for that particular workflow.

**Comment by alexec** [comment]
What about adding a link to the archived logs in the log viewer?

**Comment by simster7** [comment]
> What about adding a link to the archived logs in the log viewer?

Note that there is currently such link available:

![image](https://user-images.githubusercontent.com/614838/112499069-5a776a00-8d44-11eb-949e-75d2f6ea9fbc.png)

**Comment by alexec** [comment]
Maybe the link could be more obvious? Or perhaps it could appear after waiting for logs for say 10s?

**Comment by jacek-jablonski** [comment]
> Maybe the link could be more obvious? Or perhaps it could appear after waiting for logs for say 10s?

I think it wouldn't remove confusion. As I am in the logs viewer window. Why should I click further to really see the logs?

**Comment by alexec** [comment]
Sure. The problem here is the log viewer is complex and changing it is risky. It would better to find another way to address this issue.

**Comment by KasnocknDave** [comment]
I would like to add a usecase from our side here:
We are using `Workflows` as a CI solution, currently v2.11.7, where archived logs are shown alongside logs from pods inside the respective tab of the GUI. Now we are hesitant to upgrade to 3.x because of the change to logs and the fact, that archived logs are no longer shown. 
For devs - of all areas and seniority levels - hiding away this feedback from plain sight is a mayor downgrade, referencing `artifacts` in some link down below also demands, that they know this domain specific language and even then, they can only get it as unstyled plaintext.
Keeping pods for a long time just for logs is not really an option. 
Using `podGC strategy`, it is more of a compromise for failed workflows, but success as in `exit 0` doesn't always mean everything went as planned as well.

Lastly I want to to stress, that the work you are putting into workflows and the dashboard is highly appreciated. Especially for CI usecases this log viewer issue might be more relevant than you currently think and it would be a shame for devs not upgrading or using this because of it.

**Comment by jacek-jablonski** [comment]
In view of the above opinion and further experience, I would like to raise the topic of the log viewer again.

Some developers only develop workflows that are fired on Argo Workflows. They don't know the underlying infrastructure nor the architecture of the Argo Workflows itself.. They just fire up jobs and look at their output. Each newcomer needs to be explained why it works this way and why you can first view the logs in the window and then you have to click through the link, because the logs in the window are empty after the workflow is finished.

Why can't we just try to read the feed logs, and if it's not available, read them from the bucket? It would greatly simplify the use and, at the same time, be in line with basic intuition.

@alexec kindly please consider the above proposition, as this issue got upvoted since your last input and we can assume that other users have the same problem with this behavior :).

Thanks for your splendid work.

**Comment by alexec** [comment]
Would you like to submit a PR?

**Comment by jacek-jablonski** [comment]
If the vision of this change has a chance of being accepted and if I manage to bite in the code, I can try.
