### ISSUE TITLE
CronWorkflow schedule giving inconsistent experience

### ISSUE THREAD

**Issue by dinever** [argoproj/argo-workflows#5691]
## Summary 

This issue contains several minor issues related to CronWorkflow:

AFIAK we don't support the second-level CronWorkflow schedule. Second-level CronWorkflow will be rejected when submitting.  But the crontab translator seems to have no problem with it. This is an inconsistent user experience:

![Screen Shot 2021-04-17 at 1 00 58 AM](https://user-images.githubusercontent.com/1311594/115102381-7a034c00-9f18-11eb-8c94-413031f4b5c9.png)

Furthermore, for an existing & valid CronWorkflow, the user can actually update it to a second-level CronWorkflow, and the schedule doesn't seem to work (Next schedule time says "xx seconds ago").

![crontab](https://user-images.githubusercontent.com/1311594/115102470-fa29b180-9f18-11eb-90f1-9468e2c7d976.gif)

We should have consistent UX for this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Changes needed:

1. Fix `UpdateCronWorkflow` (server/cronworkflow/cron_workflow_server.go) to invoke `validate.ValidateCronWorkflow (like `CreateCronWorkflow` does on line 35)
2. Remove `Next Scheduled Time` (ui/src/app/cron-workflows/components/cron-workflow-status-viewer.tsx#L27-35). I think it is better to remove this feature than it to be buggy because it is based on wrong information.
3. The UI validator resides in `<PrettySchedule/>` (ui/src/app/cron-workflows/components/pretty-schedule.tsx). However, this will always only be roughly correct - and we cannot predict when it might be wrong. Instead, we should add an `<InfoIcon />` to let users know that seconds are not supported.

@dinever would you like to submit a PR?
