### ISSUE TITLE
Workflows waiting for synchronization lock cannot be filtered as "pending" in ui and CLI

### ISSUE THREAD

**Issue by arnonki** [argoproj/argo-workflows#6263]
## Summary 

What happened/what you expected to happen?

After implementing synchronization in the workflow level, I cannot filter for "pending" workflows in the UI and in the CLI 

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
3.0.7

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
kubelet

Did this work in a previous version? I.e. is it a regression?
Dont know

Are you pasting thousands of log lines? That's too much information. 

```bash
 ~ ▓▒░ argo3 list  --running                                                                                                                                    ░▒▓ ✔ | 4s |  
NAME                                           STATUS    AGE   DURATION   PRIORITY
XX  Pending   29m   0s         0
XX  Pending   29m   0s         0
XX   Pending   29m   0s         0

 ~ ▓▒░ argo3 list  --status pending                                                                                                                                  ░▒▓ ✔ |
No workflows found
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
can you provide what is the current state of the workflows `argo list` and workflow controller logs?

**Comment by arnonki** [comment]
When time passes pending workflows starts and/Users/arnon/Downloads/argo-logs.txt complete... the current state of `argo list` workflow depends on the the workflows...
[argo-logs.txt](https://github.com/argoproj/argo-workflows/files/6759595/argo-logs.txt)

argo list
```NAME                                                STATUS      AGE    DURATION   PRIORITY
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Pending     10m    0s         0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
WF-XXX-TTT        Running     10m    10m        0
```

**Comment by saranyaeu2987** [comment]
@sarabala1979 
I have similar issue. I have set synchronization to 1 but the workflows (of a cron) are not running and are in pending state.  

Here is workflow controller logs

> time="2021-07-13T14:10:01Z" level=info msg="Enforcing history limit for 'v-dim-prod-item'" namespace=argo workflow=v-dim-prod-item
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-sf7dv message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-wm4qm message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-v7xgp message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60071827 workflow=wf-joe-v-cost-sf7dv
time="2021-07-13T14:10:02Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60063871 workflow=wf-joe-v-cost-wm4qm
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-sjr7p message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60067801 workflow=wf-joe-v-cost-v7xgp
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-n2bx4 message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60050830 workflow=wf-joe-v-cost-sjr7p
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-gzj9d message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60055364 workflow=wf-joe-v-cost-gzj9d
time="2021-07-13T14:10:02Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-flx47 message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:02Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60076131 workflow=wf-joe-v-cost-n2bx4
time="2021-07-13T14:10:03Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60081407 workflow=wf-joe-v-cost-flx47
time="2021-07-13T14:10:03Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-fvttm message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:10:03Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60085507 workflow=wf-joe-v-cost-fvttm
time="2021-07-13T14:10:03Z" level=warning msg="Workflow 'v-stg-db2-ad-excp-price-jkfkj' from CronWorkflow 'v-stg-db2-ad-excp-price' completed"

**Comment by kriti-sc** [comment]
@sarabala1979 Am able to replicate the issue. Willing to pick this up. Let me know.

**Comment by kriti-sc** [comment]
Possible that the two issues above are separate, will look into both.

**Comment by sarabala1979** [comment]
Sure, please go ahead to submit PR

**Comment by kriti-sc** [comment]
@arnonki can you please try these command - `argo list  --status Pending` or `argo list  --status Pending,Running`
