### ISSUE TITLE
container logs printed on UI have a newline char in them, making long URLs non parse-able

### ISSUE THREAD

**Issue by samene** [argoproj/argo-workflows#6292]
I have a container template which prints a long URL like this on stdout

```
http://self-service-patch-generator.10.93.1.18.nip.io:32000/self-service-patch-generator/PSO-Professional-Services/IN-34567_2021-07-06T16%3A43%3A02Z.tgz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio123123%2F20210706%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210706T164503Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=d0527c2dd89c769d24520e085881654b2c11d4d5fba84da9fd23c9ed1dce37c5
```

When the logs are viewed on the UI in logs it appends a new line character to the lines and copy-pasting this URL leads to an incorrect URL. Something like this

```
http://self-service-patch-generator.10.93.1.18.nip.io:32000/self-service-patch-generator/PSO-Professional-Services/IN-34567_2021-07-06T16%3A43%3A02Z.tgz?X-A
mz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio123123%2F20210706%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210706T164503Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-
Signature=d0527c2dd89c769d24520e085881654b2c11d4d5fba84da9fd23c9ed1dce37c5
```

**Expected:**
The logs printed on URL should not add unnecessary newline characters

**Info**
Argo 3.0.7
kubernetes 1.20

**Comment by danilorsilva** [comment]
Same problema with log format:

Example:

[1m[0m
[1m[0m[1m[0m  [1m[34mdisk i/o            [1m[39m 3.600003ms
[1m[0m[1m[0m  [1m[34mparsing HCL         [1m[39m 13.377µs
[1m[0m[1m[0m  [1m[34mevaluating values   [1m[39m 161.665µs
[1m[0m[1m[0m  [1m[34mrunning checks      [1m[39m 578.709µs
[1m[0m[1m[0m  [1m[34mfiles loaded        [1m[39m 3
[1m[0m[1m[0m[1m[32m[1m[1m
No problems detected!
[1m[0m

**Comment by tczhao** [comment]
here's some workaround.. (not very pretty but works)
1. instead of paste directly to your destination, paste it on the browser url section first, then copy again (this will remove any line wrap)
or
2. instead of copy from logviewer result 
(https://host/argo/workflows/default/omniscient-dragon?tab=workflow&nodeId=omniscient-dragon&sidePanel=logs:omniscient-dragon:main),
copy from the backend call result 
(https://host/argo/api/v1/workflows/default/omniscient-dragon/log?logOptions.container=main&grep=&logOptions.follow=true&podName=omniscient-dragon)
