### ISSUE TITLE
API Docs swagger is very slow

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#6645]
Click Post /api/v1/workflows/{namespace}/submit in API Docs

![image](https://user-images.githubusercontent.com/61470342/131694493-81cede1d-8a34-446c-8e8a-6608e644d931.png)

https://github.com/swagger-api/swagger-ui/issues/1919

https://cloud-native.slack.com/archives/C01QW9QSSSK/p1630499802196400

**Comment by alexec** [comment]
Issue seems isolated to any endpoint that return a large document. Which is basically all of them.

**Comment by alexec** [comment]
We need the upstream to be fixed. The up-steam seems to have no intention of fixing this. Maybe not fixable.

**Comment by swafa** [comment]
Are there no new updates regarding that problem or anyway to avoid it? It's quite disappointing to install a correctly-configured latest version of Argo (v3.3) and still see that issue.

**Comment by agilgur5** [comment]
> Are there no new updates regarding that problem or anyway to avoid it?

Per above, since it's an upstream issue in Swagger UI as well as partially due to Argo's large Swagger spec. https://github.com/swagger-api/swagger-ui/issues/6787 is the main relevant issue but there are several [performance issues](https://github.com/swagger-api/swagger-ui/labels/cat%3A%20performance) in Swagger UI.

The only real way we might be able to mitigate this is to use a different visualizer dep entirely

**Comment by sivakrishnak12** [comment]
Hi, Any update on this? it is occuring with springdoc-openapi-starter-webmvc-ui, 2.5.0.
Is there a plan to fix this?
