### ISSUE TITLE
False deletion message when canceling workflow deletion in Argo UI

### ISSUE THREAD

**Issue by yoichiwo7** [argoproj/argo-workflows#6859]
## Summary

When you cancel workflow deletion in Argo UI, false popup message `"Performed 'DELETE' on selected workflows"` shows up.

Following steps can reproduce the bug:

1. Go to "Workflows" tab in Argo UI.
2. Select one or more workflows.
3. Click "DELETE" button and cancel it.
4. After canceling it, the target workflows aren't deleted as expected. However, green popup message `"Performed 'DELETE' on selected workflows"`shows up on the bottom-right of the UI. 

Argo Workflows Versions: 3.1.8 and 3.1.13

## Diagnostics

\-

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think this probably happens for all of these, the bug is probably here:

https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx#L55

If that method exit due to cancel, the `.then()` is still executed on this line:

https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx#L85

So the notification appears.

If `performActionOnSelectedWorkflows` returned a `boolean` indicating if the action was executed, then the `.then()` could check it.

Would you like to submit a PR to fix?

FYI @rbreeze
