### ISSUE TITLE
Cannot get k8s resource 's log ?

### ISSUE THREAD

**Issue by berlinsaint** [argoproj/argo-workflows#6910]
## Summary
Im create workflow using tfjob.
![image](https://user-images.githubusercontent.com/10629930/136898483-4018343e-50c5-4876-a55c-5ad6051a1f23.png)

how can i get  tfjob containers log except using kubectl?

**Comment by terrytangyuan** [comment]
TFJob is a custom resource so I don't think logs are available besides the main container log that basically watches for the resource status. I'd suggest using a sidecar to collect your logs from worker/master pods and inject the log to a separate container/step so that you can see via the UI. Other than that, `kubectl` is the easiest way to access the logs.
