### ISSUE TITLE
`init` process with Emissary executor

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7259]
# Summary

The emissary executor runs as PID 1, which means that the subprocess runs cannot. This is a problem for people using tools like `tiny` and `dumb-init` as their init process. They loose features like zombie process reaping.

```
tests-jobs-minutely-1637595840: [WARN  tini (22)] Tini is not running as PID 1 and isn't registered as a child subreaper.
tests-jobs-minutely-1637595840: Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
``` 

Options

1. Do nothing. The Emissary already forwards kill signals correctly. It does not reap zombies.
2. Make the Emissary take on init duties, specifically the reaping of Zombies. This is a clear improvement over other executors. [example](https://github.com/pablo-ruth/go-init/blob/master/main.go#L94) 
3. Put an init binary into the `argoexec` image (like we do in Dataflow) and wrap the emissary in that process. Easy and robust, but damages security posture.

Key lines of code

https://github.com/argoproj/argo-workflows/blob/0ea85547984583d4919b8139ffd0dc3d2bdaf05e/cmd/argoexec/commands/emissary.go#L66
https://github.com/argoproj/argo-workflows/blob/0ea85547984583d4919b8139ffd0dc3d2bdaf05e/cmd/argoexec/commands/emissary.go#L112

https://github.com/pablo-ruth/go-init/blob/30e47fe6f58c0e7fb5dfd12525b583639c7bda92/main.go#L152

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
```
diff --git a/examples/hello-world.yaml b/examples/hello-world.yaml
index 0141da684..879a8c014 100644
--- a/examples/hello-world.yaml
+++ b/examples/hello-world.yaml
@@ -2,17 +2,13 @@ apiVersion: argoproj.io/v1alpha1
 kind: Workflow
 metadata:
   generateName: hello-world-
-  labels:
-    workflows.argoproj.io/archive-strategy: "false"
-  annotations:
-    workflows.argoproj.io/description: |
-      This is a simple hello world example.
-      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
 spec:
   entrypoint: whalesay
   templates:
-  - name: whalesay
-    container:
-      image: docker/whalesay:latest
-      command: [cowsay]
-      args: ["hello world"]
+    - name: whalesay
+      container:
+        image: docker/whalesay:latest
+        command: [ sh, -c ]
+        args:
+          - |
+            sleep 15s
diff --git a/test/e2e/testdata/zombie-workflow.yaml b/test/e2e/testdata/zombie-workflow.yaml
index e69de29bb..c1b2b28e5 100644
--- a/test/e2e/testdata/zombie-workflow.yaml
+++ b/test/e2e/testdata/zombie-workflow.yaml
@@ -0,0 +1,34 @@
+apiVersion: argoproj.io/v1alpha1
+kind: Workflow
+metadata:
+  generateName: zombie-
+spec:
+  entrypoint: main
+  templates:
+    - name: main
+      container:
+        image: argoproj/argosay:v2
+        command:
+          - bash
+          - -c
+        args:
+          - |
+            set -ex
+            cat > zombie.c <<EOF
+            #include <stdlib.h>
+            #include <sys/types.h>
+            #include <unistd.h>
+            int main () {
+              pid_t child_pid;child_pid = fork ();
+              if (child_pid > 0) {
+                sleep (60);
+              } else {
+                exit (0);
+              }
+              return 0;
+            }
+            EOF
+            sudo apt-get update
+            sudo apt-get install -y build-essential
+            cc zombie.c -o zombie
+            ./zombie
\ No newline at end of file
diff --git a/workflow/executor/os-specific/signal_darwin.go b/workflow/executor/os-specific/signal_darwin.go
index 2c51e082d..69b7fe1af 100644
--- a/workflow/executor/os-specific/signal_darwin.go
+++ b/workflow/executor/os-specific/signal_darwin.go
@@ -3,6 +3,7 @@ package os_specific
 import (
 	"os"
 	"syscall"
+	"time"
 )
 
 func IsSIGCHLD(s os.Signal) bool { return s == syscall.SIGCHLD }
@@ -18,3 +19,28 @@ func Kill(pid int, s syscall.Signal) error {
 func Setpgid(a *syscall.SysProcAttr) {
 	a.Setpgid = true
 }
+
+func ReapZombies(stopCn chan struct{}) {
+	for {
+		select {
+		case <-stopCn:
+			return
+		default:
+			var status syscall.WaitStatus
+
+			// Wait for orphaned zombie process
+			pid, _ := syscall.Wait4(-1, &status, syscall.WNOHANG, nil)
+
+			if pid <= 0 {
+				// PID is 0 or -1 if no child waiting
+				// so we wait for 1 second for next check
+				time.Sleep(1 * time.Second)
+			} else {
+				// PID is > 0 if a child was reaped
+				// we immediately check if another one
+				// is waiting
+				continue
+			}
+		}
+	}
+}
diff --git a/workflow/executor/os-specific/signal_linux.go b/workflow/executor/os-specific/signal_linux.go
index 2c51e082d..69b7fe1af 100644
--- a/workflow/executor/os-specific/signal_linux.go
+++ b/workflow/executor/os-specific/signal_linux.go
@@ -3,6 +3,7 @@ package os_specific
 import (
 	"os"
 	"syscall"
+	"time"
 )
 
 func IsSIGCHLD(s os.Signal) bool { return s == syscall.SIGCHLD }
@@ -18,3 +19,28 @@ func Kill(pid int, s syscall.Signal) error {
 func Setpgid(a *syscall.SysProcAttr) {
 	a.Setpgid = true
 }
+
+func ReapZombies(stopCn chan struct{}) {
+	for {
+		select {
+		case <-stopCn:
+			return
+		default:
+			var status syscall.WaitStatus
+
+			// Wait for orphaned zombie process
+			pid, _ := syscall.Wait4(-1, &status, syscall.WNOHANG, nil)
+
+			if pid <= 0 {
+				// PID is 0 or -1 if no child waiting
+				// so we wait for 1 second for next check
+				time.Sleep(1 * time.Second)
+			} else {
+				// PID is > 0 if a child was reaped
+				// we immediately check if another one
+				// is waiting
+				continue
+			}
+		}
+	}
+}
diff --git a/workflow/executor/os-specific/signal_windows.go b/workflow/executor/os-specific/signal_windows.go
index 27c295d4d..9ff290b8a 100644
--- a/workflow/executor/os-specific/signal_windows.go
+++ b/workflow/executor/os-specific/signal_windows.go
@@ -23,3 +23,7 @@ func Kill(pid int, s syscall.Signal) error {
 func Setpgid(a *syscall.SysProcAttr) {
 	// this does not exist on windows
 }
+
+func ReapZombies(stopCn chan struct{}) {
+	// not supported
+}
```

**Comment by alexec** [comment]
I've made a few attempts to reproduce this issue, but I think we are probably dealing with orphans zombie processes correctly.

We should probably mention in the docs you do not need dumb-init with the Emissary.

**Comment by akloss-cibo** [comment]
FYI, I'm experiencing something that looks very much like this.
```
argoexec: v3.3.0
  BuildDate: 2022-03-14T21:39:34Z
  GitCommit: c6f1e4a0ece96f774f75699eba741dc85af18f31
  GitTreeState: clean
  GitTag: v3.3.0
  GoVersion: go1.17.8
  Compiler: gc
  Platform: linux/amd64
```

`ps ax` in the pod:
```
    PID TTY      STAT   TIME COMMAND
      1 ?        Ssl    0:00 /var/run/argo/argoexec emissary -- /src/ci/run
    197 ?        S      0:00 bash /src/ci/run-npm
   5361 pts/0    Ss     0:00 bash -l
   8010 ?        S      0:00 sleep 1
   8011 pts/0    R+     0:00 ps ax
   ```

**Comment by journey-wang** [comment]
> ReapZombies

Hi alexec,  why ReapZombies cannot be found in the v3.3.8 ?

**Comment by journey-wang** [comment]
@alexec

**Comment by journey-wang** [comment]
After some work, someone could try this solution for v3.3.8:

--- a/workflow/executor/os-specific/signal_linux.go
+++ b/workflow/executor/os-specific/signal_linux.go
@@ -2,7 +2,11 @@ package os_specific

 import (
        "os"
+       "os/signal"
        "syscall"
+
+       "github.com/argoproj/argo-workflows/v3/util/errors"
+       "golang.org/x/sys/unix"
 )

 func IsSIGCHLD(s os.Signal) bool { return s == syscall.SIGCHLD }
@@ -18,3 +22,67 @@ func Kill(pid int, s syscall.Signal) error {
 func Setpgid(a *syscall.SysProcAttr) {
        a.Setpgid = true
 }
+
+func Wait(process *os.Process) error {
+       // We must copy the behaviour of Kubernetes in how we handle sub-processes.
+       // Kubernetes only waits on PID 1, not on any sub-process that process might fork.
+       // The only way for those forked processes to run in the background is to background the
+       // sub-process by calling Process.Release.
+       // Background processes always become zombies when they exit.
+       // Because the sub-process is now running in the background it will become a zombie,
+       // so we must wait for it.
+       // Because we run the process in the background, we cannot Process.Wait for it to get the exit code.
+       // Instead, we can reap it to get the exit code
+       pid := process.Pid
+       if err := process.Release(); err != nil {
+               return err
+       }
+
+       c := make(chan os.Signal, 1)
+       signal.Notify(c, unix.SIGCHLD)
+
+       for {
+               // Block for an incoming signal that a child has exited.
+               // Attempt to reap all abandoned child processes
+
+       POLL:
+               // Try to reap children until there aren't any more. We
+               // never block in here so that we are always responsive
+               // to signals, at the expense of possibly leaving a
+               // child behind if we get here too quickly. Any
+               // stragglers should get reaped the next time we see a
+               // signal, so we won't leak in the long run.
+               var status unix.WaitStatus
+               wpid, err := unix.Wait4(-1, &status, unix.WNOHANG, nil)
+               if wpid == pid {
+                       return errors.NewExitErr(status.ExitStatus())
+               }
+
+               switch err {
+               case nil:
+                       // Got a child, clean this up and poll again.
+                       if pid > 0 {
+                               goto POLL
+                       }
+                       return err
+
+               case unix.ECHILD:
+                       // No more children, we are done.
+                       return nil
+
+               case unix.EINTR:
+                       // We got interrupted, try again. This likely
+                       // can't happen since we are calling Wait4 in a
+                       // non-blocking fashion, but it's good to be
+                       // complete and handle this case rather than
+                       // fail.
+                       goto POLL
+
+               default:
+                       // We got some other error we didn't expect.
+                       // Wait for another SIGCHLD so we don't
+                       // potentially spam in here and chew up CPU.
+                       return err
+               }
+       }
+}
