### ISSUE TITLE
Add option to skip workflow duration estimation

### ISSUE THREAD

**Issue by kobejn-jb** [argoproj/argo-workflows#7271]
# Summary

What change needs making?

I would like to have an option to disable workflow duration estimations in workflow-controller using setting in configMap.

# Use Cases

When would you use this?

Currently for workflows created from cronWorkflows, worfklowTemplates and clusterWorkflowTemplates controllers tries to estimate duration using previous workflow executions, at first it checks for them in kubernetes Api (existing workflow resources) in case there are none (like in my case `ttlStrategy.secondsAfterCompletion: 60` so wf's are moved to archive quickly) it checks the archive.
I've described problem with that in details here:
https://github.com/argoproj/argo-workflows/discussions/6670
In my case archive is postgres as RDS `db.t3.medium"` and I'm running ~25k workflows a day and I'm removing form archive workflows older than 20days. Controller often gets stuck waiting for response form database. It seems that this might be a problem with all argo-workflows setups with big number of daily wofklow execution. Estimation is not useful in every setup so having an ability to disable estimations would be useful feature to avoid this problems.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by NikeNano** [comment]
I can take a look at this if we want to support this feature @alexec? Makes sense to me.

**Comment by alexec** [comment]
We use an informer (i.e. in-memory) to lookup live workflows. That should be instantaneous.

Is the problem here is that the database call to requests a recent workflow is slow? It should be fast, using database indexes etc. 

I think it is probably because we make three 3 list calls, each of which should return 0 or 1 results:

https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/workflow/controller/estimation/estimator_factory.go#L79

https://github.com/argoproj/argo-workflows/blob/78c08cf2d37bd31da450e3f57bcfb0a4d6f2ee35/persist/sqldb/workflow_archive.go#L153

You can configure the controller to print the SQL it runs:

```
UPPERIO_DB_DEBUG=1
```

Or maybe (I'm not sure which, try both!):

```
UPPERIO_DB_DEBUG=true
```

Run that, then run it directly in the console to get a query plan. 

If you're running locally (e.g. `env UPPERIO_DB_DEBUG =1 make start PROFILE=mysql`) then you can connect using `make mysql-cli` which will open the MySQL console.

Here is how to use MySQL query plans:

https://dev.mysql.com/doc/refman/8.0/en/execution-plan-information.html

Create the query plan, then look for oddities. E.g. is it performing a Cartesian outer join? Table scan rather than indexed query?

Finally, it might be that @kobejn-jb has something wrong with their set-up. E.g. database somehow not correctly set-up.  Network slow. Database slow.

**Comment by agilgur5** [comment]
Linking #13382 here as another example where this option could be useful
