### ISSUE TITLE
Pod OOM causes workflow to get stuck on "Running"

### ISSUE THREAD

**Issue by alotkros** [argoproj/argo-workflows#7457]
### What happened/what you expected to happen?

During a workflow we sometimes run into an issue where a pod that goes OOM, makes the entire workflow get stuck on running until we manually interrupt the workflow.
Additionally, looking at the Argo UI shows the pod that went OOM is stuck on "Running". Possibly the workflow didn't detect that the pod went OOM - thinking it's still running hence the workflow gets stuck.

### What version of Argo Workflows are you running?

Argo 3.1.2

### What Kubernetes provider are you using?

Openshift 4.6

### What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@alotkros can you try on 3.1.15 or 3.2.6?

**Comment by naor2013** [comment]
@sarabala1979 I'll continue him because we work together.
The problem is that trying new versions in our company is a big struggle and takes a long while.
Is there a reason to suspect that any of those versions will really solve it? Did any of the recent versions try to solve this issue or something similar to it?
Or are you suggesting it just to make sure?

**Comment by sarabala1979** [comment]
@naor2013 There are a few enhancements on handling pod reconcile in the latest versions(3.1.15 and 3.2.6).   is this OOM killed node daemon?

**Comment by acj** [comment]
@sarabala1979 We've upgraded to 3.3.2 and are still seeing this issue. Can you reopen it, please? Do you have any troubleshooting suggestions?

**Comment by alexec** [comment]
@acj could I ask you to open a new issue?
