### ISSUE TITLE
Improve plugin templates docs

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7683]
* Do plugin templates only support Python? It's not clear in the docs:
  * https://github.com/argoproj/argo-workflows/blob/master/docs/executor_plugins.md
  * https://github.com/argoproj/argo-workflows/blob/master/docs/plugins.md
* Does a plugin failure cause a workflow failure? If so does it support the [continueOn](https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/examples/continue-on-fail.yaml) feature?
* How do users securely manage secrets needed for a plugin? Such as a Slack token in your example.
* Should we have an example in https://github.com/argoproj/argo-workflows/tree/master/examples for this feature? 
* Is the community going to maintain any common plugins such as a Slack plugin? 
* How do plugins interact with features such as resource requests/limits , pod disruption budgets, retry on the workflow side and activeDeadlineSeconds? It's a template so all template/step features should work right?
* What are the use cases for the aysnc / requeue feature? Is the 2 minutes configurable?

**Comment by Shark** [comment]
@alexec The Executor Plugin [example](https://github.com/argoproj/argo-workflows/blob/master/docs/executor_plugins.md#a-simple-python-plugin) is currently broken because it's missing a step. There is a Python HTTP server and the plugin is configured to run `python -c`, but the script is never referenced or copied into a Docker image.

Do you have a neat idea for baking the script into the plugin? Custom Docker image is painful just for testing. I found a hacky [Gist](https://gist.github.com/ropnop/d477ed1cf7f78c1296e0a2f20b5d925f) that could help.

**Comment by Shark** [comment]
💡 The file must have the name `server.* `.

This isn't mentioned in the docs, I'll open a PR.
