### ISSUE TITLE
Support archived workflows logs in UI from archived logs

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7830]
# Summary

Currently, if you open an archived workflow, you are not able to see logs in the log viewer, even if the logs were archived to 'main.log'. We could fix this.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tczhao** [comment]
Hi @alexec , would you mind providing more details on this.
I couldn't get my head around what you meant by "Support archived workflows logs in UI from archived logs".
All I'm thinking right now is we can view archived log from archived workflows

**Comment by noam-codefresh** [comment]
If I understand correctly - the current UI does not make the request to get the logs (output artifacts) by the workflow's UID? because the server's endpoint for it exist.

**Comment by asfaltboy** [comment]
Does this relate to the Log UI "All" option not showing nothing after pods are garbage collected? Or, should that be considered a separate issue?

On a side note, what does this recommendation in [the docs](https://argoproj.github.io/argo-workflows/configure-archive-logs/) mean?:

> ⚠️ We do not recommend you rely on Argo Workflows to archive logs. Instead, use a conventional Kubernetes logging facility.

Are there some known issues? Also, does kubernetes provide any facility for collecting and returning logs for garbage collected pods, and then can argo workflows use this facility? I ask because viewing logs in the argo workflows UI is very convenient, and one of the main "selling points" of the application in my mind

**Comment by agilgur5** [comment]
> Also, does kubernetes provide any facility for collecting and returning logs for garbage collected pods, and then can argo workflows use this facility?

A pretty conventional cluster set-up is to have `fluentd` / `fluent-bit` as a DaemonSet collecting logs from all nodes and sending those a log provider (e.g. Splunk, Logstash, etc).
That would be an interesting feature if Workflows could use it, as it is indeed convenient. As a workaround to that, you can add an [external link](https://argoproj.github.io/argo-workflows/links/) to a query in your log provider.

**Comment by agilgur5** [comment]
Not sure if #11121 ended up fixing this as well

**Comment by terrytangyuan** [comment]
It's supported. Re-open if not.
