### ISSUE TITLE
Pod deletions with large workflows

### ISSUE THREAD

**Issue by gandeevan** [argoproj/argo-workflows#7994]
## Summary

I’ve been running large scale jobs (~1K parallel jobs, each of which spawns around ~100 tasks in parallel) on an argo cluster deployed on GKE and I’ve been seeing a quite a few “pod deleted” errors. On further investigation, it looks like the the main container finishes to completion, but GKE pod garbage collector deletes the pod before the workflow controller updates the workflow status. I have already configured retries, but that doesn’t seem to really help since a lot of the retried jobs are failing for the same reason. The default terminated-pod-gc-threshold is around 12500, which explains why I see this issue only at scale.Would appreciate any help to workaround this problem. Thanks!

What executor are you using? PNS/Emissary
PNS

Argo v3.2.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gandeevan** [comment]
No, we are not using the autopilot feature. I think it's the pod garbage collector kicking in when the # of terminated pods exceed the `--terminated-pod-gc-threshold` (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/). 

Based on the application logs, it looks like the pod ran to completion and the k8s garbage collector GC'ed the terminated pod before the worfklow controller could examine the pod status. I was able to confirm my hypothesis by examining the controller logs and cluster audit logs, I see the following sequence of events: 

- `io.k8s.core.v1.pods.patch` request from the node on which the pod is executing at 9:36:37 am PST to update the `workflows.argoproj.io/outputs` annotation. 
- `io.k8s.core.v1.pods.delete` request from the k8s pod-garbage-collector at 9:37:59 am PST
- Workflow controller updates the node phase from Running -> Error at 9:38:52 am PST.

I'm not sure if a pdb would help here, since the pod ran to completion and was GC'ed by k8 in a terminated state.

**Comment by gandeevan** [comment]
@alexec would the fix for this be under the scope of https://github.com/argoproj/argo-workflows/issues/7996?

**Comment by alexec** [comment]
I think #7966 would improve the situation. But we can do something better, we could add a finalizer to each pod which is only removed by workflow controller when the pod is GCed.

**Comment by alexec** [comment]
To block GC, add a finalizer:

https://github.com/argoproj/argo-workflows/blob/de1f4f50e61b08eed1dbddcb167cab00f4bd2b97/workflow/controller/workflowpod.go#L205

I would call this finalizer `workflows.argoproj.io/capture-result`. It should be opt-in based on an environment variable (e.g. `ARGO_RESULT_CAPTURE_FINALIZER=true`.

The finalizer must be removed when the controller has captured the outcome. This should be robust, nothing more annoying than removing finalizers when a controller broke. 

Firstly, we must remove the finalizer if we want delete the workflow:

You'll need to queue one of these for each pod in the workflow that has the finalizer, there would be here:

https://github.com/argoproj/argo-workflows/blob/de1f4f50e61b08eed1dbddcb167cab00f4bd2b97/workflow/controller/controller.go#L875

I'd introduce a new func to do this `wfc. removeAllPodCaptureResultFinalizers(namespace,workflowName)`. This func can use the pod informer to find all pods for the workflow, and then filter them by which have the finalizer.

I'd therefore introduce a `wfc.removeCaptureResultFinalizer(namespace,podName)`. This should ignore 404 errors (due to race conditions).

We should not block pod deletion until the workflow is deleted. We should delete pods when we want to GC them.

Output captured happens after one of the following:

* The pods is marked as completed (i.e. the `/completed` annotation is added to it).
* The GC tries to delete the pod.

Both of these have a pod clean-up action. We can add a call to `wfc.removeCaptureResultFinalizer 
 each of them.

https://github.com/argoproj/argo-workflows/blob/de1f4f50e61b08eed1dbddcb167cab00f4bd2b97/workflow/controller/controller.go#L529

**Comment by alexec** [comment]
@gandeevan I've added on outline solution if you want to submit a PR.

However, this may just move your problem.

**Comment by gandeevan** [comment]
Thanks for the pointer @alexec! I can definitely work on the fix, will probably take some time though since I'd have to ramp up with the argo-workflows code base. 

I'm not sure I understand why would it move the problem, instead of fix it? Do you mind explaining that. Thanks!

**Comment by alexec** [comment]
By "move" I mean that the pod will no longer be deleted, but you might have a new problem because new pod cannot be created.

**Comment by alexec** [comment]
You may wish to request a mentor if you want help.

**Comment by gandeevan** [comment]
Why do you say that there could be a new problem because new pod cannot be created? AFAIK the terminated-pod-gc-threshold doesn't limit the number of pods in the cluster. 

Also, how is the output captured (e.g. output parameter), passed on to the next step in the workflow? Would it be okay to remove the finalizer before the output is captured (as mentioned in the proposed solution)?

**Comment by alexec** [comment]
Ok, maybe try and see?

**Comment by clementemmanuel** [comment]
@gandeevan did you ever resolve this? I'm also facing what I believe to be the same issue.

**Comment by tooptoop4** [comment]
did u solve @gandeevan ?

**Comment by rahulsh1** [comment]
would #9058 address this issue?
