### ISSUE TITLE
Viewing Archived Workflows when RBAC is Namespace Delegated - Bug?

### ISSUE THREAD

**Issue by BhavikaSharma** [argoproj/argo-workflows#8498]
Hi, I'm wondering if there's a potential bug when when using namespace delegation for RBAC. I have a service account in a namespace that has permissions to view workflows in the namespace. I'm able to log in, and through a group, bind to the service account. This allows me to view workflows in the namespace.

From the logs, I see:

```
time="2022-04-26T20:53:26.926Z" level=info msg="selected SSO RBAC service account for user" email=<redacted> loginServiceAccount=user-default-login serviceAccount=default ssoDelegated=true ssoDelegationAllowed=true subject=<redacted>
```

However, when accessing archived workflows from the UI, I receive an error:
```
time="2022-04-26T17:54:01.366Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2022-04-26T17:54:01Z" grpc.time_ms=2.549 span.kind=server system=grpc
time="2022-04-26T17:54:01.376Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = Permission denied, you are not allowed to list workflows in namespace \"<redacted>\". Maybe you want to specify a namespace with `listOptions.fieldSelector=metadata.namespace=your-ns`?" grpc.code=PermissionDenied grpc.method=ListArchivedWorkflows grpc.service=workflowarchive.ArchivedWorkflowService grpc.start_time="2022-04-26T17:54:01Z" grpc.time_ms=15.412 span.kind=server system=grpc
```

From the logs, I see:

```
time="2022-04-26T20:52:30.920Z" level=info msg="selected SSO RBAC service account for user" email=<redacted> loginServiceAccount=user-default-login serviceAccount=user-default-login ssoDelegated=false ssoDelegationAllowed=false subject=<redacted>
```
When I expected to see the same logs as regularly accessing the workflows page. 

It seems like [this](https://github.com/argoproj/argo-workflows/blob/e12827b8b0ecb11425399608b1feee2ad739575d/server/auth/gatekeeper.go#L274) function is returning false for archived workflows. Wondering if anyone else is seeing this/if this is a potential bug. Thanks!

_Originally posted by @BhavikaSharma in https://github.com/argoproj/argo-workflows/discussions/8497_

**Comment by alexec** [comment]
@basanthjenuhb ?

**Comment by basanthjenuhb** [comment]
So `ListArchivedWorkflowsRequest` is implemented differently.
It doesn't have a namespace parameter.
Namespace is passed as a `FieldSelector`
Hence currently this will not work

so to fix this, 2 options
1. Write custom code to handle `ListArchivedWorkflowsRequest` requests which don't have a namespace request
2. Modify `ListArchivedWorkflowsRequest` and then it should automatically work. (And make sure future apis built should have a namespace parameter)

@alexec I think we should do option 2. WDYT ?


@BhavikaSharma A workaround that you can use is  to give READ access to workflows for `user-default-login`.
Since SSO is not delegated, the read access of `user-default-login` will be used.

**Comment by basanthjenuhb** [comment]
Other requests like `RetryArchivedWorkflowRequest`, `ResubmitArchivedWorkflowRequest` have a namespace parameter.
Not sure why `ListArchivedWorkflowsRequest` was implemented differently.

**Comment by alexec** [comment]
So we're saying they cannot be supported. We should probabyl document that.

**Comment by basanthjenuhb** [comment]
We can support, just that the request needs to be modified to add a namespace parameter.
For ListArchivedWorkflowsRequest and couple of others.
Shall i make a PR with this approach ?

**Comment by alexec** [comment]
I don't think we should fix this. @juliev0 work will deprecate this endpoint. Users should move to use the next endpoint. We could put a 301 redirect in place

**Comment by jessesuen** [comment]
> I don't think we should fix this. @juliev0 work will deprecate this endpoint. Users should move to use the next endpoint. We could put a 301 redirect in place

@alexec Why do we need a new endpoint to replace this one -- what would be so different about the Request signature that it needs a new endpoint?

**Comment by alexec** [comment]
The current endpoints don't container the namespace in the URL, so we cannot use GetNamespace to perform namespaced RBAC on them. The current endpoints don't support directories. I'd like to consolidate them into a single endpoint to reduce the amount of code, the  amount of bugs, the amount of security problems.

**Comment by hbrewster-splunk** [comment]
+1

**Comment by msuthar-splunk** [comment]
Can we please reopen this? This issue is impacting us as well.

**Comment by terrytangyuan** [comment]
> I don't think we should fix this. @juliev0 work will deprecate this endpoint. Users should move to use the next endpoint. We could put a 301 redirect in place

@alexec What work are you referring to from @juliev0? 

@basanthjenuhb Would you be interested in working on this issue?

**Comment by juliev0** [comment]
> > I don't think we should fix this. @juliev0 work will deprecate this endpoint. Users should move to use the next endpoint. We could put a 301 redirect in place
> 
> @alexec What work are you referring to from @juliev0 that will deprecate the endpoint?
> 
> @basanthjenuhb Would you be interested in working on this issue?

I guess Alex was referring to the fact that we now have this endpoint:
`mux.HandleFunc("/artifact-files/", artifactServer.GetArtifactFile)`

in addition to the endpoints we had before:
```
mux.HandleFunc("/artifacts/", artifactServer.GetOutputArtifact)
mux.HandleFunc("/input-artifacts/", artifactServer.GetInputArtifact)
mux.HandleFunc("/artifacts-by-uid/", artifactServer.GetOutputArtifactByUID)
mux.HandleFunc("/input-artifacts-by-uid/", artifactServer.GetInputArtifactByUID)
```

I think he's thinking we'd replace those last 4 with the first once, since I believe it should be able to do the same thing. I'm not sure if this is a priority at the moment, though, although certainly reducing the code is always a good thing. Moreover, I don't know that the new endpoint would necessarily take care of this issue (would it @alexec?). If @basanthjenuhb is able to help with this issue it would be great.

**Comment by basanthjenuhb** [comment]
@juliev0 
Is the new endpoint integrated with the UI ?
Let me have a look at the new endpoint. It should be easily fixable.

**Comment by basanthjenuhb** [comment]
Also, generally issues are prioritized by 👍 count on the issue subject.
This issue didn't have any, probably why it got deprioritized.
Would request people to add a 👍 on the issue subject at the top.
This would help maintainers to prioritize.

**Comment by juliev0** [comment]
> @juliev0 Is the new endpoint integrated with the UI ? Let me have a look at the new endpoint. It should be easily fixable.

It is as far as the "artifact visualization" at least (being able to click on the artifact and view it). That's when the new endpoint was added (GED week).

**Comment by christophkreutzer** [comment]
Still an issue, sorry bot :(

**Comment by msuthar-splunk** [comment]
Still an issue. Commenting to keep it relevant.

**Comment by terrytangyuan** [comment]
@juliev0 @alexec What's the relationship between artifacts endpoints and this specific issue?

@basanthjenuhb Could you elaborate on why passing namespace as part of the field selector causes the issue?

**Comment by juliev0** [comment]
> @juliev0 @alexec What's the relationship between artifacts endpoints and this specific issue?
> 
> @basanthjenuhb Could you elaborate on why passing namespace as part of the field selector causes the issue?

Now I am re-reading the comments above. I see Alex was saying that the namespace wasn't part of the original endpoint, but I'm actually not sure what endpoint that is offhand. The new endpoint is this one:
`mux.HandleFunc("/artifacts/", artifactServer.GetOutputArtifact)` which does take a namespace.

**Comment by jessesuen** [comment]
> The current endpoints don't container the namespace in the URL, so we cannot use GetNamespace to perform namespaced RBAC on them. The current endpoints don't support directories. I'd like to consolidate them into a single endpoint to reduce the amount of code, the amount of bugs, the amount of security problems.

@alexec - if we mandate namespace as part of url fragment as a set of `v2` endpoints, it also means we are removing the current ability to list archived workflows *across namespaces*:

<img width="651" alt="Screen Shot 2022-12-02 at 12 07 09 PM" src="https://user-images.githubusercontent.com/12677113/205377062-8465a077-f279-41ac-9c54-d597c25b6ce9.png">

Therefore, to preserve this functionality, I think it is actually **_appropriate_** for namespace to be an *optional* query parameter to the URL. 

So I propose the implementation would be:
* if incoming request does not have query parameter for a namespace, they are asking for workflows in all namespace. So then we check if they can have cluster scoped list workflows privileges
* otherwise, if incoming request does have namespace query param, we can just check to see if they have workflow get privileges for that namespace.

This is no different than Kubernetes's RBAC where it's possible to either: (a) list all workflows in the cluster vs. (b) list workflows in a namespace.

**Comment by christophkreutzer** [comment]
This is still relevant for us.
@basanthjenuhb anything we could help here?

**Comment by emagana-splunk** [comment]
@jessesuen  @terrytangyuan  Are you folks working on this issue? Any ETA?

**Comment by juliev0** [comment]
@basanthjenuhb @terrytangyuan Sorry for any comments above related to the Artifact endpoint. This has nothing to do with Artifacts, but back when I wrote that I'd just assumed that the reason Alex had named me as being the one to deprecate the endpoint was because I'd worked on the new Artifacts endpoint, and at the time I was still relatively ignorant about Workflows not to know better. :) 

@basanthjenuhb If you don't have bandwidth either I or somebody else can take this on.

**Comment by basanthjenuhb** [comment]
@juliev0 Thank you, please go ahead

**Comment by juliev0** [comment]
@jessesuen @basanthjenuhb I have implemented the approach you mentioned, Jesse.  ListArchivedWorkflowsRequest now takes an optional namespace. What was once a field selector is now an optional query parameter. Draft PR is [here](https://github.com/argoproj/argo-workflows/pull/10399/files).

One thing is that I know [archivedWorkflowServer.ListArchivedWorkflows()](https://github.com/juliev0/argo-workflows/blob/8498-sso-rbac-archives/server/workflowarchive/archived_workflow_server.go#L40) is also called by the CLI and by our client libraries. Do you think we should still support the namespace-as-a-field-selector in order to maintain backward compatibility with these? (and maybe it's an error if both are specified and they conflict?)
