### ISSUE TITLE
`make start` is too verbose

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8759]
Because:

* `LOG_LEVEL=debug` in `Makefile` when it could be `LOG_LEVEL=info`
* `LEADER_ELECTION_IDENTITY=local` in `Procfile` when it could be `LEADER_ELECTION_DISABLE=true`

**Comment by TheSwarnim** [comment]
Hi @alexec, I want to work on this issue. I'm new here, so just want to confirm that I just have to change `debug` to `info` in `LOG_LEVEL` and the same with `LEADER_ELECTION_IDENTITY`

**Comment by deepanshululla** [comment]
I created PR #9001  for this. Please let me know if any further changes are needed. Thanks.

**Comment by measutosh** [comment]
Hi @alexec , I am new and want to work on this issue. I see @deepanshululla has raised a PR([9001](https://github.com/argoproj/argo-workflows/pull/9001)) and the issue has not been solved since then . Could you please suggest can we move forward with the changes he has made or some other thing needs to be modified.
