### ISSUE TITLE
CRITICAL Vulnerability CVE-2022-1996 found in image for v3.3.8

### ISSUE THREAD

**Issue by divyaArthurAI** [argoproj/argo-workflows#9149]
The docker image for argoproj/argo-workflows:v3.3.8 (https://github.com/argoproj/argo-workflows/releases/tag/v3.3.8) is flagging vulnerability [CVE-2022-1996 ](https://nvd.nist.gov/vuln/detail/CVE-2022-1996). 

The vulnerability appears to come from the underlying argo docker images (argoexec, argocli, workflow-container). The :latest images for these (in docker and quay) no longer have the vulnerability. Can you please rebuild the image to use the latest images and release a new version?

**Comment by terrytangyuan** [comment]
We should be releasing v3.4 at some point soon. Not sure which specific commits fixed the issues but we might want to backport them. cc @sarabala1979 @alexec

**Comment by alexec** [comment]
I can't see either. I think this should back-ported.

**Comment by tojaroslaw** [comment]
Sorry to bug y'all, but do either of you have an estimate on when 3.4 will be released?

**Comment by divyaArthurAI** [comment]
Looks like the vulnerabilities, that were scanning clean in the :latest image 11 days ago, are now flagging again as of today. 

@alexec @terrytangyuan - Any idea on which commit fixed/reverted the issue and if v3.4 will have a fix ?

**Comment by terrytangyuan** [comment]
I don't see any related commits that would cause this. @divyaArthurAI Are you continuously monitoring it and did the issue just start to appear again yesterday?

**Comment by divyaArthurAI** [comment]
@terrytangyuan I scanned the argoexec:latest image from docker 12 days ago and they were clean and then I scanned the argoexec:latest image yesterday and it appeared again.

**Comment by mcgrawia** [comment]
For clarity, [CVE-2022-1996](https://nvd.nist.gov/vuln/detail/CVE-2022-1996) is not actually a vulnerability in Argo Workflows. The problem is Argo is dependent on a vulnerable version of the [emicklei/go-restful](https://github.com/emicklei/go-restful) package. To fix this, Argo needs to update to a version of emicklei/go-restful >= v3.8.0. It looks like today Argo uses version `v2.15.0` of go-restful based on the [go.mod file in master](https://github.com/argoproj/argo-workflows/blob/master/go.mod#L125).

**Comment by alexec** [comment]
@divyaArthurAI is quite correct. There is a daily Githhub Action  that runs Snyk and detects issues. You can see that the "go" job has failed:

https://github.com/argoproj/argo-workflows/runs/7512800278?check_suite_focus=true

You can run this yourself locally:

```
brew install snyk
snyk test --file=go.mod
```

Because this is bough in by Argo Events, that needs updating. It will also need releasening (v1.7.2) before Argo Workflows can take the fix.

@divyaArthurAI to help progress this, would you like to update Argo Events?

I have another ask, you've not told us how you identified this issue?

**Comment by mcgrawia** [comment]
Hi @alexec, I'm speaking for @divyaArthurAI here but we run nightly scans of all of our containers using an open source tool called [Trivy](https://github.com/aquasecurity/trivy). Our nightly scan started failing ~2 weeks ago because of CVE-2022-1996, which flagged in all of our Argo Workflow images.

**Comment by alexec** [comment]
Thank you. There can be only one. Will Snyk win, or Trivy? :)

@mcgrawia you seem to know this problem. Would you like to contribute the fix?

**Comment by mcgrawia** [comment]
Sure thing! I think someone from our team can start looking into it. Can you give any guidance on where the go-restful dependency comes from? I see in [Argo Events it's also listed as indirect](https://github.com/argoproj/argo-events/blob/master/go.mod#L155), which makes me think it comes from something further downstream.

**Comment by alexec** [comment]
Yes.

https://github.com/argoproj/argo-events

**Comment by mcgrawia** [comment]
Right, but even in Argo-Events it is listed as an indirect dependency, meaning it comes from something else that Argo Events depends on if I'm not mistaken. Do you have any insight into what dependency brings in go-restful to Argo Events? If Argo Events was using it directly, I would expect it to be a direct dependency.

**Comment by mcgrawia** [comment]
@alexec @terrytangyuan created PR here, let me know if there's anything else I can do:

https://github.com/argoproj/argo-events/pull/2111
