### ISSUE TITLE
Support Azure Storage account as default artifact repo

### ISSUE THREAD

**Issue by Transmitt0r** [argoproj/argo-workflows#9595]
This is a new issue based on my comment in #1540

Azure File storage support is now available for artifacts, but it can not be used as defaultArtifactRepo yep.
Now that minio gateway is being deprecated, this seems like an important thing to add to support deployments on Azure.

> Does this support having azure blob storage as the default artifact repo? I can't seem to get it working

Same, when I try to use azure as defaultArtifactRepo, the configmap is empty except this exception:
```
apiVersion: v1
data:
  config: "containerRuntimeExecutor: emissary\nartifactRepository:\n  s3:\n    accessKeySecret:\n
    \     key: accesskey\n      name: \n    secretKeySecret:\n      key: secretkey\n
    \     name: \n    bucket: \n    endpoint: \n    insecure: false\n"
kind: ConfigMap
...
```

_Originally posted by @Transmitt0r in https://github.com/argoproj/argo-workflows/issues/1540#issuecomment-1236655890_

**Comment by terrytangyuan** [comment]
You need to use the latest version, at least 3.4.

**Comment by Transmitt0r** [comment]
Ah, then the doc's have not been updated yet as of [v3.4.0-rc4](https://github.com/argoproj/argo-workflows/blob/v3.4.0-rc4/docs/configure-artifact-repository.md#configure-the-default-artifact-repository). Do you maybe also know in which PR/commit this was introduced?

**Comment by terrytangyuan** [comment]
It's added in https://github.com/argoproj/argo-workflows/pull/9026 by @brianloss. @brianloss Would you like to help update the documentation?

**Comment by brianloss** [comment]
It's already documented on that page in the [table at the top](https://github.com/argoproj/argo-workflows/blob/v3.4.0-rc4/docs/configure-artifact-repository.md#configuring-your-artifact-repository) and with a [detailed section](https://github.com/argoproj/argo-workflows/blob/v3.4.0-rc4/docs/configure-artifact-repository.md#configuring-azure-blob-storage)
I can also add a comment or another section under the [Configure the Default Artifact Repository](https://github.com/argoproj/argo-workflows/blob/v3.4.0-rc4/docs/configure-artifact-repository.md#configure-the-default-artifact-repository) header since it seems to be confusing to not have it there.
