### ISSUE TITLE
Finalizer for kubernetes resources created by a workflow

### ISSUE THREAD

**Issue by boniek83** [argoproj/argo-workflows#9855]
# Summary

I want to make sure that kubernetes resource created by a workflow is deleted when workflow fails or is deleted. Currently using onExit doesn't guarantee that. I can run kubectl delete workflow <workflow-name> - it will skip onExit, I can run argo terminate (or press terminate in UI) - it will skip onExit. What happens if argo itself stops working?

Probably related to https://github.com/argoproj/argo-workflows/issues/7860
# Use Cases

I want to make sure that SparkApplications (that use a lot of resources) started by a Workflow die with a Workflow.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Use resource template and specify ownerReference.

**Comment by terrytangyuan** [comment]
Could you clarify what you meant by "stops working correctly"? That only sets a owner reference.

**Comment by Joibel** [comment]
Owner references cannot cross namespaces.

**Comment by boniek83** [comment]
So there is no support for cleaning up resources created by workflow in different namespaces than workflow itself?

**Comment by Joibel** [comment]
> So there is no support for cleaning up resources created by workflow in different namespaces than workflow itself?

No integrated support, no.

Your use case is very much a corner case. You're:
* violating namespace boundaries (when you could probably avoid doing that, which would fix this).
* directly deleting `Running` workflows rather than ensuring they are completed in some form.

Whilst it would technically be possible to add support to fix this issue, it's not something I think is the right thing to do as it adds quite a lot of complexity, has workarounds, and has not had interest from others.

**Comment by boniek83** [comment]
Fair enough.
